### ISSUE TITLE
readutils: extract.obs fails for pre-filtered cmicor and any(vec.obs>1)

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#10]
The consistency check in `extract.obs` prevents extracting observables with CMI ID > 1 when the correlator files have been read with the `obs` argument.

expected behaviour: A cmicor object created by, say, `readcmidatafiles` with the argument `obs=c(5)` contains only one observable with ID 5. `extract.obs` should allow the extraction of this observable.

actual behaviour: extract.obs quits with the error message `extract.obs: data inconsistent, nrObs in the data does not match to input data length``

I don't fully understand the reason for this consistency check, it seems to be illogical, since `cmicor` can very well have only one observable with any ID imaginable... I would just remove the consistency check, but there may be a valid reason for it being there, I just can't see it.

**Comment by kostrzewa** [comment]
One could imagine adding a consistency check like:
```if( !all( unique(vec.obs)) %in% unique(cmicor[,ind.vec[1]]) )){ fail }```

**Comment by kostrzewa** [comment]
@urbach I could really use an opinion on this if you have some time because I'm doing the pi0 right now and would like to get this sorted...

**Comment by urbach** [comment]
@kostrzewa sorry, I overlooked this issue. Can you provide me with something to reproduce this problem?

**Comment by kostrzewa** [comment]
Could you define "something"? If you mean data, then any of the correlators that we used in the past should work fine (with multiple observables).

My hurry, btw, just got reduced substantially because the filesystems in Zeuthen were taken offline due to problems, so I'm getting the nf=2+1+1 neutral pion inversions going at HLRN instead...

```
files <- getorderedfilelist(basename="...",path="...")
cmicor <- readcmidatafiles(files,obs=c(5))
obs <- extract.obs(vec.obs=c(5),sign=...) # fails
```

The reason is the test in the first few lines of extract.obs because calling ```readcmidatafiles``` in the way that I call it above will result in a cmicor with just one observable with ID "5". In the check in ```extract.obs```, there will then be a comparison like: ```if(5<1) { fail }```

**Comment by urbach** [comment]
hmm, why didn't I hit this problem yet...?

**Comment by urbach** [comment]
but thats tricky...

**Comment by kostrzewa** [comment]
You probably never used ```cmicor <- readcmidatafiles(files,obs=c(5))``` and loaded all observables instead. That's my current workaround but it uses more memory (as you describe in the readutils documentation) and it takes quite a bit longer because more data is being shuffled in the assignment only to be filtered out in the next line. It doesn't occur for ```obs=c(1)```, which is why I only hit it now (because before was always loading all observables)

**Comment by kostrzewa** [comment]
> but thats tricky...

explain?

**Comment by urbach** [comment]
It seems to me that indeed your proposal

    if( !all( unique(vec.obs)) %in% unique(cmicor[,ind.vec[1]]) )){ fail }

should work. As it is the test doesn't make much sense for the current version.

**Comment by kostrzewa** [comment]
OK, thanks for checking, I'll submit a pull-request sometime today or tomorrow morning!

**Comment by urbach** [comment]
Well, I can also include it directly, second...

**Comment by kostrzewa** [comment]
Okay, sure that's fine too :)

**Comment by urbach** [comment]
done, maybe you can check...

**Comment by urbach** [comment]
actually, the `unique` is even superfluous

**Comment by kostrzewa** [comment]
Thanks, will check as soon as those filesystems come back online! True, depends on what is faster, I thought %in% builds an NxM matrix internally, so I thought it would be useful to make this as small as possible.

**Comment by urbach** [comment]
yes, probably you are right.

**Comment by kostrzewa** [comment]
So this seems to work fine but I've found another (**silent!**) bug in readcmidatafiles and readcmifiles when the "obs" argument has ```length(obs)>1``` ... look at the timeslices :)

```
cmicor12 <- readcmidatafiles(files,obs=c(1,2))
print(cmicor12)
[...]
19839  1  7  1  8.571969e+00  7.967369e+00
19840  1  7  3  1.371206e+00  1.115243e+00
19841  1  7  5  7.607770e-01  5.916864e-01
19842  1  7  7  5.066637e-01  3.425710e-01
19843  1  7  9  3.134992e-01  2.401209e-01
19844  1  7 11  2.190475e-01  1.379077e-01
19845  1  7 13  1.502958e-01  7.825544e-02
19846  1  7 15  9.210434e-02  5.347306e-02
19847  1  7 17  5.797154e-02  5.381678e-02
19848  1  7 19  3.710534e-02  4.094955e-02
19849  1  7 21  2.787625e-02  3.217475e-02
19850  1  7 23  2.364325e-02  2.783423e-02
19851  2  1  1  1.125523e+00 -1.080482e+00
19852  2  1  3  1.365160e-02 -1.174356e-02
19853  2  1  5 -3.630360e-03  7.111216e-04
19854  2  1  7  1.816858e-03  5.295503e-03
19855  2  1  9  2.256786e-03  1.845668e-03
19856  2  1 11  1.529912e-03  1.986958e-03
19857  2  1 13  1.419228e-03  2.144716e-03
19858  2  1 15  2.687362e-04  1.499651e-03
19859  2  1 17 -1.040006e-04  7.791962e-04
19860  2  1 19  9.562414e-05  1.109565e-03
19861  2  1 21  4.994352e-05  7.163810e-04
19862  2  1 23  3.364230e-05  2.707569e-04
[...]
```

Now this is not necessarily a bug because "obs" is meant to extract a single observable, but I guess it should ```stop()``` when ```length(obs)>1```

**Comment by urbach** [comment]
Maybe I did this on purpose. Why do you think this should not be possible?

**Comment by kostrzewa** [comment]
Hmm.. To be honest I'm also a bit surprised that it doesn't work...

**Comment by kostrzewa** [comment]
Something very strange is happening there... so if you read a single correlator and then do the filtering manually, I would expect the comparison to be a vector with two sequences of TRUE:
```
cor <- read.table(skip=1,file="outprcv.xx.yyyy")
cor[,1]==c(4,5)
[...]
 [301]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [313]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [325]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [337]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [349]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [361]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [373]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [385]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [397]  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [409] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [421] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [433] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [445] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [457] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [469] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [481] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [493] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE
 [505] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[...]
```
but instead I get this alternating TRUE,FALSE, which then clearly selects every n'th timeslice. The fix would be to use the ```%in%``` operator instead.

**Comment by kostrzewa** [comment]
I think we might have fixed this already.
