### ISSUE TITLE
fit.plateau2cf is broken

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#103]
The function `fit.plateau2cf` currently is broken because the `boot.samples` parameter is no longer part of the function signature.

Apart from that, the point of the function seems really strange: Why would we want to fit a constant to the correlation function?

**Comment by kostrzewa** [comment]
we had discussed this some months ago: constants are fitted to ratios of correlation functions  for the computation of current insertions between hadronic states, such as for form factors. Not every type of correlation function decays exponentially...

**Comment by martin-ueding** [comment]
Okay, that makes sense, I forgot about that.

Then I would suggest that we should just add another model to the new set of matrixfit models which is just a constant.

**Comment by martin-ueding** [comment]
I think I fixed it now in PR #101. It only works with a bootstrapped correlation function, but that isn't really any hindrance.

**Comment by martin-ueding** [comment]
Once PR #88 is through, we can probably just add a constant model and remove this function altogether.
