### ISSUE TITLE
use complex data type for correlation functions

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#105]
This is a somewhat fundamental question which would involve significant changes throughout the entire code base. While complex correlation functions are currently supported at least in principle via the ```icf``` member, in practice there are only few functions which currently duplicate their functionality also for the imaginary part. Importantly, none of the ```summary``` or ```plot``` do.

This duplication could be avoided by using a complex type, but quite a few helper routines would have to be adjusted, for instance to plot both real and imaginary parts (if desired).

Having native support for complex correlation functions will make it easier to deal with, for example, the combination of the connected and disconnected parts of three-point functions at non-zero momentum.

**Comment by kostrzewa** [comment]
@urbach This can be avoided, of course, if one is certain that all types of correlation functions (and parts of correlation functions) can be pre-processed to extract the relevant part. For example, when I have a three-point function at non-zero momentum transfer built from a two-point function with different momenta at sink and source and a loop with the appropriate momentum transfer, can I determine à priori that the parts relevant to the signal are, for example, the real part of the two-point function and the imaginary part of the loop? (just as an example)

**Comment by kostrzewa** [comment]
An alternative idea would be to have a "raw correlator" type which would be complex and matrix-valued (for generality), which is used to form products of raw correlators, perform spin (and possibly flavour) projections and from which the signal part is then extracted into a ```cf``` after all transformations have been performed.

**Comment by kostrzewa** [comment]
I would really appreciate if we could discuss / decide this quickly so I can begin implementing the changes / additions because we need a way to at least load and pre-process complex and possibly matrix-valued correlation functions in several projects.

**Comment by kostrzewa** [comment]
After some thought, I've come to the conclusion that the easiest and most reasonable way forward is to introduce a new type which I've called ```raw_cf```. This will be of complex numeric mode and support arbitrary internal dimensions (beyond measurement and time) to accommodate matrix-valued correlators.

```
raw_cf[meas, time, dim1, dim2, ..., dimN]
```

Once all transformations (time-shifts, gamma matrix multiplications, multiplications or ratios of multiple correlation functions etc.) have been performed to form analysable objects, this type can then be converted into ```cf``` for final analysis.

```raw_cf``` will, for the beginning, not support bootstrapping or jackknifing. Instead, errors will be calculated using uwerr since these are only really required to get an idea of the signal quality and for that, taking into account auto-correlations is the sensible thing to do.

This should give us the necessary flexibility to analyse all the data from current and upcoming projects.

**Comment by urbach** [comment]
Hi Bartek,

sounds reasonable. I'll not be able to work a lot these days, please go ahead...

Carsten

On 28 December 2018 15:53:19 CET, Bartosz Kostrzewa <notifications@github.com> wrote:
>After some thought, I've come to the conclusion that the easiest and
>most reasonable way forward is to introduce a new type which I've
>called ```raw_cf```. This will be of complex numeric mode and support
>arbitrary internal dimensions (beyond measurement and time) to
>accommodate matrix-valued correlators.
>
>```
>raw_cf[meas, time, dim1, dim2, ..., dimN]
>```
>
>Once all transformations (time-shifts, gamma matrix multiplications,
>multiplications or ratios of multiple correlation functions etc.) have
>been performed to form analysable objects, this type can then be
>converted into ```cf``` for final analysis.
>
>```raw_cf``` will, for the beginning, not support bootstrapping or
>jackknifing. Instead, errors will be calculated using uwerr since these
>are only really required to get an idea of the signal quality and for
>that, taking into account auto-correlations is the sensible thing to
>do.
>
>This should give us the necessary flexibility to analyse all the data
>from current and upcoming projects.

-- 
Carsten Urbach mobile

**Comment by martin-ueding** [comment]
Having a separate data type for this sounds good. This also means that we can remove all the `icf` handling from the `cf` class and make that a pure real correlator?

**Comment by kostrzewa** [comment]
Work on this is now in #107
