### ISSUE TITLE
interactive() is problematic for "my" typical usecase

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#11]
They way I use R makes the usage of `interactive()` a bit problematic. My analysis drivers have loads of parameters in order to be suitable for different analyses (as far as that is possible) and as a result I generally run them from an interactive session. It would be helpful for me if interactivity as a reason for calling `X11()` to get new windows could be an internal state rather than what is reported by `interactive()`. What do you think?

**Comment by urbach** [comment]
so you mean an additional parameter?

I usually run `Rscript`...

**Comment by kostrzewa** [comment]
> I usually run Rscript...

That doesn't really work for me since my drivers are themselves functions, I guess I could write further R scripts which call the drivers, rather than calling them "interactively". I guess that would even be a good way to keep track of the exact parameters used for a given analysis. Lemme think about it and I'l get back to you.

> so you mean an additional parameter?

I guess so, but more usefully it could also be done through the options() framework, with the default as ```TRUE``` and this can then be handled locally for the various cases where you've used ```interactive``` 
```
if( (is.null(getOption("hadron.interactive") || getOption("hadron.interactive")) && interactive()) { x11() }
```
or something like that. The ```is.null()``` would ensure backwards compatibility.

**Comment by kostrzewa** [comment]
I would really like to re-iterate this point. I don't think that a plot routine should open new devices...

**Comment by urbach** [comment]
I don't see, why not. There is not other way to have multiple X11 plots opened by a single plot function. However, I see your point. So, what about something like the following additional condtions to `interactive()`

    grepl("X11", names(dev.cur()), ignore.case=TRUE) || grepl("null", names(dev.cur()), ignore.case=TRUE)

to only open a new window if there is no other driver used than X11?

**Comment by urbach** [comment]
See commit 82aed149802804a05b28e5f51dd03a08277b9553 ...

**Comment by urbach** [comment]
in urbach/hadron master branch

**Comment by kostrzewa** [comment]
Yes, I think so, I'll close the issue.
