### ISSUE TITLE
Hook for compiling documentation

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#118]
I seem to forget to check in compiled documentation from time to time. As we had already discussed it is not desired to force the user to run `devtools::document()` before being able to install the code. Apart from publishing it on CRAN or having Travis CI deploy the documentation to `master` we might be able to do this with a pre-commit hook.

From what I recall one cannot simply change the files and hope that they make it into the commit. From what I read just now one has to additionally stage the files. This can be done, but it might cause some troubles when there are changes which are not staged and so on. If we want to continue checking in the documentation along with the changes, such a hook could be helpful.

**Comment by kostrzewa** [comment]
Yeah, we should do this. It seems like it's not much of a hassle to set up. ```devtools::document()``` can be run and should then terminate in a way that makes it possible for the pre-commit hook to return non-zero in case documentation was updated and zero otherwise.

In the case that the return was non-zero, the commit will be aborted, allowing the updated documentation to be checked in.

**Comment by kostrzewa** [comment]
Ah, but wait! The problem that we faced, if I remember correctly, is that hooks are in the ```.git``` directory and cannot be version-controlled...

**Comment by kostrzewa** [comment]
And while one could include a local ```.gitconfig``` which modifies ```core.hooksPath```, one still needs to tell git (interactively) to actually parse this ```.gitconfig```, as far as I understand...

**Comment by martin-ueding** [comment]
That's easy to fix: We put them into `hooks` and then symlink `hooks` to `.git/hooks` with a script that every user has to execute once.

**Comment by martin-ueding** [comment]
We will have to diff the diff before and after `devtools::document()` ran. *That* will then have an exit status.

**Comment by kostrzewa** [comment]
Yeah, it works.

**Comment by martin-ueding** [comment]
> once in every copy of the repository that one might keep locally to be able to work on multiple checked out branches with unstaged modifications

Are you aware of `git-worktree` (`git help worktree`)?

**Comment by martin-ueding** [comment]
I also realized this, that should be addressed with Pull Request #120.
