### ISSUE TITLE
χ² DOF

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#137]
Our χ² fits have `dof <- length(y) - length(par)`. Excuse the perhaps stupid question, but shouldn't it be one less degree of freedom, `dof <- length(y) - length(par) - 1`?

**Comment by kostrzewa** [comment]
I think what we use is "correct" in the "usual" sense. The simplest example to see that is one with ```dof=1```. Let's say we use chi^2 to compute the mean (perhaps weighted) of N observations of some value (this could be a plateau fit, for example). Our chi^2 is

```
\chi^2 = \sum_i \frac{ (X_i - \bar{X})^2 }{ \sigma_{X_i}^2 }
```

and our fit parameter is ```\bar{X}```.  For a given value of ```\bar{X}``` that we get out as our best fit, only ```n-1``` of the ```X_i``` are independent as we can deduce the final one from the sum. In other words, we have an equation (up to weight factors)

```
\sum_i r_i = \sum_i (x_i - \bar{x}) = 0
```

restricting our residuals.  So this gives our number of degrees of freedom. As we increase the number of parameters, more equations of this type can be established for our residuals.

There is a caveat, however, as soon as weights or full covariance play a role. How many degrees of freedom are there really if some subset is highly correlated? What if priors are involved? What about fit functions of the form ```f(A,B,C) = A cos(b + cx)```?

I enjoyed reading this https://arxiv.org/pdf/1012.3754 at some point although I haven't really let it inform my fitting choices...

**Comment by urbach** [comment]
asked the other way around: where should this additional dof be eaten up?

> I think what we use is "correct" in the "usual" sense. The simplest example to see that is one with ```dof=1```. Let's say we use chi^2 to compute the mean (perhaps weighted) of N observations of some value (this could be a plateau fit, for example). Our chi^2 is
> 
> ```
> \chi^2 = \sum_i \frac{ (X_i - \bar{X})^2 }{ \sigma_{X_i}^2 }
> ```
> 
> and our fit parameter is ```\bar{X}```.  For a given value of ```\bar{X}``` that we get out as our best fit, only ```n-1``` of the ```X_i``` are independent as we can deduce the final one from the sum. In other words, we have an equation (up to weight factors)
> 
> ```
> \sum_i r_i = \sum_i (x_i - \bar{x}) = 0
> ```
> 
> restricting our residuals.  So this gives our number of degrees of freedom. As we increase the number of parameters, more equations of this type can be established for our residuals.
> 
> There is a caveat, however, as soon as weights or full covariance play a role. How many degrees of freedom are there really if some subset is highly correlated? What if priors are involved? What about fit functions of the form ```f(A,B,C) = A cos(b + cx)```?
> 
> I enjoyed reading this https://arxiv.org/pdf/1012.3754 at some point although I haven't really let it inform my fitting choices...
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/HISKP-LQCD/hadron/issues/137#issuecomment-456910325
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
> I think what we use is "correct" in the "usual" sense. The simplest example to see that is one with `dof=1`.

Sorry, I meant ```dof=n-1```.
