### ISSUE TITLE
plot.uwerr opens lots of windows by default

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#138]
I created an `uwerr` object for each variable of the DAG-HMC project and then wanted to plot them all. Usually plots get caught in RStudio and then neatly displayed as a list of plots. With `plot.uwerr` I get a bunch of windows:

![auswahl_001](https://user-images.githubusercontent.com/976924/51615771-f6b94280-1f28-11e9-9e13-fcd310831a91.png)

Passing `x11 = FALSE` cures that problem, but I do not get why this is the default here while all the other plot functions seem to work without that. With that option the output is as expected:

![auswahl_002](https://user-images.githubusercontent.com/976924/51615977-692a2280-1f29-11e9-8727-bfe69f673ae2.png)

**Comment by kostrzewa** [comment]
This is one of the functions that one often uses interactively and the only way to do that usefully is to open new windows. I also find this annoying and much prefer just plotting to a file and looking at the file. The current behaviour is a compromise between @urbach and me :)

**Comment by martin-ueding** [comment]
So if you use it interactively on the command line the various `plot` commands would just open a single window and then overwrite the previous plot? I see that this is not what we want. But shouldn't this then also occur in `plot.matrixfit`, which does the QQ-plot?

**Comment by kostrzewa** [comment]
Yes, in the QQ-plot we perhaps managed to correctly auto-detect this. We might want to port the fix from there.

**Comment by kostrzewa** [comment]
> So if you use it interactively on the command line the various `plot` commands would just open a single window and then overwrite the previous plot?

Yep.

**Comment by martin-ueding** [comment]
The code in `plot.matrixfit` has this:

```r
    if(interactive() && (grepl(pattern="X11", x=names(dev.cur()), ignore.case=TRUE) || grepl(pattern="null", x=names(dev.cur()), ignore.case=TRUE))) {
      X11()
    }
```

And the one in `plot.uwerr` has this:

```r
    if(x11) if(interactive() && (grepl(pattern="X11", x=names(dev.cur()), ignore.case=TRUE) || grepl(pattern="null", x=names(dev.cur()), ignore.case=TRUE))) {
              X11()
            }
```

It looks exactly the same to me. I assume that the difference is that the first plot in `plot.matrixfit` is done to the default device whereas `plot.uwerr` calls `X11()` directly for the first plot. I have tried that in RStudio and it works as expected:

![auswahl_001](https://user-images.githubusercontent.com/976924/52181461-644f5380-27f2-11e9-8e5d-12be66245aa0.png)

From this I would conclude that this calling `X11()` is okay for subsequent plots, but the first plot should go to the default device. On the CLI this *should* be X11, but for RStudio it seems to be some PNG-like thing where it writes temporary files.

I'll extract this as a function and then we can use it everywhere.
