### ISSUE TITLE
rhdf5lib version issues

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#139]
how do we resolve the ```Rhdf5lib``` issue? Using the newest version of ```rhdf5``` requires it, but that in turn requires ```R >= 3.5```. Should we just depend on an older version of ```rhdf5``` for the time being? Without a workaround, ```R CMD check``` fails right-away.

**Comment by martin-ueding** [comment]
I think that we just depend on `rhdf5` and let it decide whether it needs that dependency. Then from Bioc we pull in the `release` version, which should work out. That [seemed to work out for Carsten](https://github.com/HISKP-LQCD/hadron/pull/111#issuecomment-452705868) and Travis CI.

**Comment by kostrzewa** [comment]
So we should remove ```Rhdf5lib``` from our Suggests

**Comment by martin-ueding** [comment]
PR #111 will do that. It removed it from `Remotes`, and I have now also removed it from `Suggest` there.
