### ISSUE TITLE
plot.bootstrapfit cannot plot complex-valued functions

### ISSUE THREAD

**Issue by maowerner** [HISKP-LQCD/hadron#155]
I used bootstrap.nlsfit to fit a function `f: \mathbb{R} \to \mathbb{C}`. This is possible by having the fit function wrapper return a pair of values `(\mathbb{R}, \mathbb{R})`. Unfortunately the plot function just yields
```
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ
```
because it cannot vizualize two dependent variables at once. I propose to extend `plot.bootstrapfit` by a parameter `post_transformation` with default value `id`. This would not affect any existing code, but allows to specify how to visualize non-obvious cases e.g. by passing `Re`, `Im` or something more subtle.

**Comment by maowerner** [comment]
I would like to seperate the calculation of `Y` and `polyval` - the values to plot - from the actual plotting. After discussing with Johann I feel like extending the functionality without breaking the plotting is much more complicated than necessary.

```
  ## to include additional parameter to x$fn originally given as ... to
  ## bootstrap.nlsfit requires some pull-ups
  Y <- do.call(x$fn, c(list(par = x$t0[1:npar], x = X, boot_r = 0), x$tofn))

  ## error band
  ## define a dummy function to be used in apply
  prediction_boot_fn <- function (boot_r) {
    par <- x$t[boot_r, 1:npar, drop = FALSE]
    do.call(x$fn, c(list(par = par, x = X, boot_r = boot_r), x$tofn))
  }
  predictions <- do.call(rbind, lapply(1:nrow(x$t), prediction_boot_fn))
  se <- apply(predictions, 2, error, na.rm = TRUE)
  stopifnot(length(se) == length(X))

  ## plot it
  polyval <- c(Y+se, rev(Y-se))
  if(any(polyval < my.ylim[1]) || any(polyval > my.ylim[2])) {
    polyval[polyval < my.ylim[1]] <- my.ylim[1]
    polyval[polyval > my.ylim[2]] <- my.ylim[2]
  }
```

**Comment by maowerner** [comment]
plot.bootstrapfit implicitly features `x` more prominently by visualizing it as the x-axis. Johann and I agreed that we would basically have to rewrite the whole nlsfit routine to have multiple equally important independent variables. 

The optimal balance between development effort and functionality would be to leave additional independent variables in the `tofn` parameter as is currently done. If it should be visualized, the refactored value calculation would just use a custom `tofn`.

This would allow the user to filter the values of `tofn` for each combination of additional custom variables wanted and call the plot routine with the desired color and line type as supported visualizers and `replot = TRUE`. This approach will not allow something like 3d plots or alpha values or hatched error bands, but something like a global fit with one or two nominal variable it will work.

**Comment by martin-ueding** [comment]
We will shortly have `predict.bootstrapfit`. Using this, one can then do some custom plotting.
