### ISSUE TITLE
Eigenvalue sorting in GEVP wrong below t0

### ISSUE THREAD

**Issue by urbach** [HISKP-LQCD/hadron#156]
for t < t0 we have to reverse the sorting order, I think this is currently not done.

This might explain why principal correllator plots look as they do and also, why the pc model is not working as expected.

**Comment by maowerner** [comment]
It does not always work. Below is a plot for D15.48 with t0 = 8 where you see the intended effect with thermal state removal but not without:
![selection_011](https://user-images.githubusercontent.com/7326707/52955384-ced4c780-338c-11e9-8ac1-4d60d3bde145.png)
There is, however no consistent behavior depending on the thermal state treatment.

**Comment by urbach** [comment]
how did this look like before the patch?

**Comment by urbach** [comment]
how do you sort?

**Comment by maowerner** [comment]
Here is a before picture:

![selection_012](https://user-images.githubusercontent.com/7326707/53011098-d1442980-343f-11e9-93a2-8d833e8bbafc.png)

For sorting I use the default parameters: 
```sort.type = "vectors", sort.t0 = TRUE```

**Comment by kostrzewa** [comment]
Any chance that you could produce these plots with slightly smaller symbols, vertical facets and more stringent lower y plot limit? It's really quite hard to see what's going on.

**Comment by kostrzewa** [comment]
> vertical facets

and those should of course be tall enough to see everything...

**Comment by urbach** [comment]
thats really strange, are you sure you used the new code everywhere?

**Comment by maowerner** [comment]
@kostrzewa Like that?

![d15 48issue-156-new](https://user-images.githubusercontent.com/7326707/53016925-17ed5000-344f-11e9-9f29-5b52d91434d7.png)
![d15 48issue-156-old](https://user-images.githubusercontent.com/7326707/53016926-17ed5000-344f-11e9-92cb-2dfcd7e0578b.png)

Yes, I am sure I used the new code everywhere.

**Comment by urbach** [comment]
But how is that possible? ?
Carsten Urbach, www.carsten-urbach.eu

**Comment by maowerner** [comment]
I will rerun the complete analysis over night to completely rule out the possibility of inconsistent data but I checked the creation dates ... I can't think of anything in the rho analysis that would erroneously  cause such a behavior.

**Comment by kostrzewa** [comment]
> I will rerun the complete analysis over night to completely rule out the possibility of inconsistent data but I checked the creation dates ... I can't think of anything in the rho analysis that would erroneously cause such a behavior.

Would it be a good idea to test this on an MWE instead?

**Comment by maowerner** [comment]
> Would it be a good idea to test this on an MWE instead?

What's a MWE?

**Comment by kostrzewa** [comment]
Minimal Working Example

**Comment by kostrzewa** [comment]
Could you set ```sort.t0 = FALSE```? From the discussion @ #157 and a quick reading of the logic, it seems clear that when ```sort.t0 == TRUE```, sorting is done using the eigenvectors at ```t0 + 2``` only. When ```sort.t0 == FALSE```, sorting is attempted for each point.

**Comment by kostrzewa** [comment]
That's even explained in ```?gevp``` ...

**Comment by urbach** [comment]
> That's even explained in ```?gevp``` ...

yes, of course. I know what it does, but don't remember why it was
`t0 + 2`...

**Comment by kostrzewa** [comment]
> yes, of course. I know what it does

sorry, I was not saying that you didn't, I was just stating that it was indeed documented

> but don't remember why it was `t0 + 2`...

my hunch would be that some of the sorting methods would fail when done at t0 directly

**Comment by maowerner** [comment]
The new version seems to work on first glance. Please find below the plot from before, with fix156 merged into the master. 
![selection_015](https://user-images.githubusercontent.com/7326707/53253522-c0a2e600-36c1-11e9-819f-82bdb2e6bb76.png)
From briefly going through the plots it looks like the eigenvalue are consistent before and after t0 now.

**Comment by urbach** [comment]
excellent!
