### ISSUE TITLE
Dependency abind not resolved correctly

### ISSUE THREAD

**Issue by maowerner** [HISKP-LQCD/hadron#161]
When installing the new version of hadron I get 
```
Error: Dependency package(s) 'abind' not available.
In addition: Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'abind' not available.
Execution halted
```

Is it intended that I have to install abind or should that be in some dependency file?

**Comment by kostrzewa** [comment]
It's a package that you need to install. Once on CRAN, these things will be resolved automatically for end users at least.

**Comment by maowerner** [comment]
I thought it might be intended that it was resolved automatically already. Installing it was not a problem obviously.
