### ISSUE TITLE
Release branch instead of commit-hook and stuff

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#162]
These days I was asked to clean up a mess partially to blame to the commit hook. Somebody wanted to commit changes, the hook aborted the commit. Instead of following the instructions by the hook, that person pulled in `origin/master` in the hope to fix things. The result was an uncommited merge with a bunch of novel changes as well as merge conflicts. A lot of things went wrong, but if that first commit would have passed, it wouldn't have ended that bad.

Then today Markus saw ripples from an incorrectly generated Rcpp export file being commited.

Besides the long `diff` and `log` output, this is starting to eat more of my time than I'd like.

The problem that we want to solve is that non-expert users (who aren't the target group anyway?) can just download and install the hadron library, right? The more important part perhaps is that one can download the library on a machine without needing `devtools` and `roxygen`. I have a new proposal: We have a “release” branch with all the generated files checked in. Users can just clone that. Then there is a “development” branch which does not have *any* generated files whatsoever. I'll create a `make-release.sh` script which takes a clean “development” commit, generates all the files and checks them into the “release” branch. This way I can focus on the “development” branch, have clean diffs, avoid merge conflicts in generated files and all the other things I dislike about the current approach. And still there is a branch to download and install right away.

The caveat is that releases have to be generated manually. But I presume that only stable versions would be used by non-expert users in non-complete environments. And also the “release” branch must never be merged into “development” branch. These changes would have to be cherry-picked or rebased then.

Implementing this can either be with `master`+`devel` or with `release`+`master`. The first one has the advantage that just cloning the repository will give you a working version. The second has the advantage that pull requests are automatically created against the correct branch. I think I prefer the first option as that 

Would that approach be acceptable?

**Comment by martin-ueding** [comment]
Context for Rcpp: https://github.com/HISKP-LQCD/hadron/commit/b1352882865dd43508ec081afdec8969281f7b9d

**Comment by kostrzewa** [comment]
> Context for Rcpp: b135288

The Rcpp file in ```master``` is correct. Seems to me that merging with master regularly would have solved the troubles...

**Comment by kostrzewa** [comment]
I prefer the first option too. The problem that I see, however, is that people will clone the master branch, make modifications and the submit pull-requests, potentially bringing in all the files that you want to keep out (and designing a gitignore for this might be challenging, since we have generated and hand-written doc, for example... ). There will be headaches, but then again, how many people are going to contribute, really?

**Comment by kostrzewa** [comment]
> who aren't the target group anyway?

At least potentially, even a Bachelor student might be asked to use hadron for a thesis topic. That's about as non-expert as it's going to get.

**Comment by martin-ueding** [comment]
Regularly merging with the *current* `master` would have solved this, yes …. But although you and I are aware of this, not everyone who contributes is. And it might be easier to have a system which is less fragile.

> At least potentially, even a Bachelor student might be asked to use hadron for a thesis topic. That's about as non-expert as it's going to get.

With Carsten considering using Rmarkdown in the next “Computerphysik” lecture I could imagine that `hadron::plotwitherror` will either be provided as a single function or perhaps these people are going to install hadron on their systems. Perhaps at that stage it should be in CRAN already, though.

Regarding people doing changes in `master`: Yes, that will certainly happen. If there is no commit-hook the changes should be easily be rebased into `devel`. But “easily rebased” is certainly not something somebody commiting on `master` would be able to do. With the other model one would have to tell people to install the `release` branch, which might also lead to many confused souls.

> then submit pull-requests

We could just close all these requests and make them rebase and open a new pull request. I guess one of us then has to help them rebasing their stuff …

> and designing a gitignore for this might be challenging, since we have generated and hand-written doc, for example

Simple: Just mark the branch protected on GitHub and then people cannot break it. If only admins can make releases we should be safe.

---

Having `master`+`devel` means no entry hurdle for plain users and a little burden on developers. We might have to close a few pull requests, but I hope we would have to do this at maximum once per person.

To me it seems that this is a bit better than the ripples caused by the generated files. Bartek, I read your comments such that you would also prefer this? Carsten, what do you think?

**Comment by martin-ueding** [comment]
@urbach, do you have an opinion on this?

**Comment by urbach** [comment]
> @urbach, do you have an opinion on this?

sorry for my late reply. What about simply generating the docu just
before we merge the pull request?

**Comment by urbach** [comment]
this is fixed for the time being, I belive...
