### ISSUE TITLE
uwerrprimary does not return the error on Gamma

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#17]
The `uwerrprimary` function returns a `list` with lots of variables, but the error on Gamma is missing. It is computed as needed in the `plot.uwerr` function. I'd like to extract the data and plot with some different package, therefore I'd need this data directly.

I have looked into the code and in `uwerrprimary` there is a `GammaFbb` which seems different from the `GammaFbb` that is used in `plot.uwerrprimary`.

Could the error on Gamma be also included in the return value of this function?

*Update*: It seems that I cannot use the `gammaerror` function in my own script because that does not get exported into the main namespace, it seems. I suppose this is a function with file-scope only, then.

*Update*: I managed to import the `uw.R` source file and then just copied the needed code from the plotting routine. So I have the data that I want, so this issue can wait.

**Comment by martin-ueding** [comment]
It's not urgent, I got the data that I need, so everything is fine.

**Comment by urbach** [comment]
still needed?

**Comment by urbach** [comment]
And, `prot.uwerr` does return the autocorrelation function with error bars.
