### ISSUE TITLE
new_matrixfit test fails at line 90

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#171]
It seems that something has changed which makes this "just" fail (result is ```1.04e-6```, tolerance is ```1e-6```)

@urbach, can you try to address this in #170 as this is currently blocking the merge

**Comment by kostrzewa** [comment]
I think it will be sufficient to modify the tolerance to ```1e-5```, depending on statistics a difference in the sixth digit is completely fine

**Comment by urbach** [comment]
> It seems that something has changed which makes this "just" fail (result is ```1.04e06```, tolerance is ```1e-6```
> 
> @urbach, can you try to address this in #170 as this is currently blocking the merge

yes, I can, but I have no idea what is going on. It is not related to
my change, I think.

**Comment by kostrzewa** [comment]
> yes, I can, but I have no idea what is going on. It is not related to my change, I think.

Agreed that it's unrelated, not sure why it popped up. Perhaps @martin-ueding knows more?
