### ISSUE TITLE
bootstrap.nlsfit with ```use.minpack.lm = FALSE``` fails

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#173]
code complains about ```boot_r``` being an unused argument of ```fn``` when the codepath with ```use.minpack.lm = FALSE``` is chosen, even if ```fn``` is wired up to accept and consume ```...```

**Comment by urbach** [comment]
> code complains about ```boot_r``` being an unused argument of ```fn``` when the codepath with ```use.minpack.lm = FALSE``` is chosen, even if ```fn``` is wired up to accept and consume ```...```

I have the same problem with ```use.minpack.lm = TRUE```. This renders
`bootstrap.nlsfit` basically useless? why is it passed to fn?

**Comment by kostrzewa** [comment]
Inside ```boostrap.nlsfit```, the fit function is called via a ```fitchi``` or ```fitchisq``` function. This in turn is called via a wrapper which is passed ```boot_r``` as an argument which is hence forwarded to ```fitchi``` and then to the fit function.

The reason is that in order to evaluate the fit function, one might need more than just ```x``` and ```y``` values. One might need the results of prior fits, for example, on the original data and the bootstrap samples.

In the way that it's currently implemented, one passes this additional data via ```...``` as vectors containing original data and bootstrap samples. As this is generic and can accept any number of additional arguments, the wrapping code cannot pass each sample of each additional data vector individually (although one could set it up to be able to do so, given restrictions on what can be contained in ```...```). Instead, the index of the current bootstrap sample is passed via ```boot_r```, such that the fit function can resolve the additional data.

In ```bootstrap.nlsfit```, see https://github.com/HISKP-LQCD/hadron/blob/a00e8c674e9a1d20d53e85c9896f7379df0b3616/R/bootstrap.nlsfit.R#L440

For an example of upper level code calling ```bootstrap.nlsfit```, see ```LuescherAnalysis```: https://github.com/kostrzewa/LuescherAnalysis/blob/master/R/breit_wigner.R

I think the fix is simply to update the documentation to ```bootstrap.nlsfit``` to indicate that the fit function must accept ```boot_r``` as an argument, even if it is just a dummy.

**Comment by urbach** [comment]
> Inside ```boostrap.nlsfit```, the fit function is called via a ```fitchi``` or ```fitchisq``` function. This in turn is called via a wrapper which is passed ```boot_r``` as an argument which is hence forwarded to ```fitchi``` and then to the fit function.
> 
> The reason is that in order to evaluate the fit function, one might need more than just ```x``` and ```y``` values. One might need the results of prior fits, for example, on the original data and the bootstrap samples.
> 
> In the way that it's currently implemented, one passes this additional data via ```...``` as vectors containing original data and bootstrap samples. As this is generic and can accept any number of additional arguments, the wrapping code cannot pass each sample of each additional data vector individually (although one could set it up to be able to do so, given restrictions on what can be contained in ```...```). Instead, the index of the current bootstrap sample is passed via ```boot_r```, such that the fit function can resolve the additional data.
> 
> In ```bootstrap.nlsfit```, see https://github.com/HISKP-LQCD/hadron/blob/a00e8c674e9a1d20d53e85c9896f7379df0b3616/R/bootstrap.nlsfit.R#L440
> 
> For an example of upper level code calling ```bootstrap.nlsfit```, see ```LuescherAnalysis```: https://github.com/kostrzewa/LuescherAnalysis/blob/master/R/breit_wigner.R
> 
> I think the fix is simply to update the documentation to ```bootstrap.nlsfit``` to indicate that the fit function must accept ```boot_r``` as an argument, even if it is just a dummy.

I agree, there are other parameters missing in the docu, too...

**Comment by kostrzewa** [comment]
I still don't fully understand, however, why it errors out at present. It seems to me that given the setup, it should be sufficient for the fit function to accept ```...```.

**Comment by kostrzewa** [comment]
An MBE (minimal broken example :) ) might be in order.

**Comment by j-ostmeyer** [comment]
> It seems to me that given the setup, it should be sufficient for the fit function to accept ...

This always worked for me. Do you have an MBE or any update?

**Comment by j-ostmeyer** [comment]
@kostrzewa you said that you fixed that by now? Has there been a pull request? Can the issue be closed?
