### ISSUE TITLE
Investigate data.table as an underlying storage format for cf and raw_cf

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#174]
I would like to propose that we investigate if we can move to ```data.table``` as an internal storage container for ```cf``` and ```raw_cf```.

The main reason for the proposal is that ```data.table``` supports true "update by reference", such that a container's data can be updated without causing deep copies. This means that if one were to initialise a ```cf``` or ```raw_cf``` object to contain data of a given size, one would subsequently be able to populate this data incrementally using function hierarchies of any depth.

This is somewhat important considering that we generally deal with the following situation:

1) we have container files (h5, say), which contain thousands of correlators for a single gauge configuration
1) opening a container is expensive and one would like to issue only a single ```H5Fopen``` (or similar) and read all relevant correlators from this container in one go
1) generally, one would store these thousands of correlators in separate objects for organisational reasons (organised by momentum configuration or other properties)
1) at the time of first initialising a new ```cf``` or ```raw_cf``` object, the total size is generally known (one knows how many files one has to read in total and thus knows how many measurements will eventually be in ```cf``` or ```raw_cf```)
1) growing an array dynamically is expensive (at some point, prohibitively so)
1) starting with a fixed sized array and populating it incrementally is currently not possible "by reference": the entire ```cf``` will be copied back and forth repeatedly

What do you think?

**Comment by urbach** [comment]
```data.table``` is part of which package?

**Comment by kostrzewa** [comment]
https://cran.r-project.org/web/packages/data.table/index.html

**Comment by kostrzewa** [comment]
@martin-ueding It might similarly make sense to perhaps investigate ```data.table``` also for paramvalf.

**Comment by martin-ueding** [comment]
Instead of incremental reduction I would rather do a `do.call(rbind, stuff)` in the end. Then `rbind` would allocate an array that is large enough. Incrementally growing a list hopefully is O(1) in R. For paramvalf I do not see where I could use it as the `value` is created via an `lapply` effectively, there is no appending going on.

**Comment by kostrzewa** [comment]
> Instead of incremental reduction I would rather do a do.call(rbind, stuff) in the end

As this has to happen inside a library function to be comfortable, it still implies passing your ```stuff``` and getting back a container with ```stuff``` "rbound" (in case of ```cf```) or "abound" (in the case of ```raw_cf```) into its data element (```cf``` in the case of ```cf``` and ```data``` in case of ```raw_cf```). It's better, of course, than the current situation, as ```stuff``` will be passed by reference and only a single copy will be made. I guess this is actually worth trying to begin with.

>  For paramvalf I do not see where I could use it as the value is created via an lapply effectively, there is no appending going on.

I was thinking to use it as a way to limit the amount of data duplication, but it's also not quite clear to me how to do this in practice yet.

**Comment by kostrzewa** [comment]
> Instead of incremental reduction I would rather do a do.call(rbind, stuff) in the end. Then rbind would allocate an array that is large enough. Incrementally growing a list hopefully is O(1) in R. For paramvalf I do not see where I could use it as the value is created via an lapply effectively, there is no appending going on.

So adding list elements is not quite O(1) as the (nested) list grows, but it's not too bad (there are fluctuations with some additions taking about three times as long as the average), but it's okay. There is some overhead, however, in that one generally ends up with a list ordered

```
corrs[[file_idx]][[corr_idx]]
```

as one is reading "all correlators" from each file. Subsequently, one needs to reshape this to

```
corrs[[corr_idx]][[file_idx]]
```

in order to use rbind (which works nicely in an mclapply over the ```corr_idx```). The overhead for the reshaping is very small but the rbind calls amount to about 1/5 of the total I/O time. Still, I was a able to squeeze a factor of ```(6 x NThreads)``` of speedup by moving to a nested list intermediate format and only creating the containers in the end.

**Comment by kostrzewa** [comment]
A major drawback is, however, that I now have the correlators in a list rather than a hash and there is a noticeable overhead when they are passed as a part of the value of a ```pv_call```. At the end of the I/O operation, I could of course transfer the contents of the correlator list

```
corrs[[corr_type]]
```

to a hash and subsequently use that to remove the list copy overhead.

**Comment by kostrzewa** [comment]
Moving to a hash format in the end seems to improve performance somewhat as it appears that access to list elements is slower than access to hash elements (by some factor of 1.4 or so). This way, working with the data later is a little faster.

**Comment by kostrzewa** [comment]
Unfortunately it seems that this doesn't really scale very well. When you have something like

```
corrs <- mclapply(
  X = 1:nfiles,
  FUN = function(file_idx){
    res <- list()
    for( corr_idx in 1:ncorrs ){
      res[[corr_idx]] <- read_corr(...)
    }
     return(res)
  }
}
```

This works great up to some total number of entries (nfiles x ncorrs), at which point it slows down to a crawl (as also reflected by the CPU load). I think it may even stall completely...

It seems to me that for working with really "big data", there is no real alternative to pre-allocation...

**Comment by kostrzewa** [comment]
This really is a "pull all your hair out and scream" moment...

**Comment by kostrzewa** [comment]
I might have found a solution, although I'm not quite sure whether it will scale all the way to the final analysis with many ensembles and hundreds of GB of raw data (although there are of course workarounds for that too, such as splitting things up to produce per-ensemble raw correlator data and only recombining it at a later stage in the analysis. A more general help would be the lazy loading in paramvalf, but I need to investigate that first.).

Using a nested ```lapply``` inside an ```mclapply``` seems to help somewhat and prevents the stalls that I've seen.

```
corrs <- mclapply(
  X = 1:nfiles,
  FUN = function(file_idx){
          lapply(X = 1:ncorrs,
                 FUN = function(corr_idx){
                         read_corr(file_idx, corr_idx)
                       }
                 )
         }
  )
```

However, the situation is still far from satisfactory as one pays quite some overhead compared to pre-allocation and multi-threaded population (it is unclear to me, however, if ```data.table``` would not balk under multi-threaded write access to different rows).
