### ISSUE TITLE
fit.effectivemass for t>T/2 documentation

### ISSUE THREAD

**Issue by j-ostmeyer** [HISKP-LQCD/hadron#18]
Thank you for allowing t > T/2 in the fit.effectivemass routine!
Could you please also update this in the documentation?

**Comment by urbach** [comment]
fixed in master branch of urbach/hadron

> Thank you for allowing t > T/2 in the fit.effectivemass routine!
> Could you please also update this in the documentation?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/hadron/issues/18
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu
