### ISSUE TITLE
bootstrap.nlsfit function reference may cause giant environment to be attached to return value

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#187]
~Does anyone actually require the resampled data in the`$bsamples` field of the value returned by `bootstrap.nlsfit`? In order to save memory and hard-drive space, I would very much like to remove it.~

~If there is opposition I will just remove it manually after using the function.~

**Comment by martin-ueding** [comment]
I think that we had a discussion about this already. I prefer the functions to only yield their result because with the paramvalf framework I can always reproduce what data went in. Other people have a workflow where they seem to drop the inputs and want the result to have an audit trail of the things that went in there.

So from my viewpoint we can happily get rid of that duplication of input.

**Comment by kostrzewa** [comment]
It seems that my memory problems with `bootstrap.nlsfit` objects definitely do not stem from the bootstrap samples. I also realised that the bootstrap samples are kind of useful if one wants to rerun `get.errors` after the fact. One might still want to consider removing them as they could grow to several MB in cases with many bootstrap samples and large fit windows.

**Comment by kostrzewa** [comment]
The problem seems to be that the function `fn` is in the return value. This causes the entire environment to be attached for some reason. Below a listing in which a bunch of `bootstrap.nlsfit` have been performed with their return values stored in a nested list. For each `[...]_leave_out_%03d`, the n'th element of the `boostrap.nlsfit` return value was `NULL`ed out.

The fifth element in the return value is `fn`...

```
-rw-r--r-- 1 bartek theorie 3.4G Oct 22 10:57 test_bootstrap_nlsfit_leave_out_001.rds
-rw-r--r-- 1 bartek theorie 3.4G Oct 22 10:57 test_bootstrap_nlsfit_leave_out_002.rds
-rw-r--r-- 1 bartek theorie 3.4G Oct 22 10:58 test_bootstrap_nlsfit_leave_out_003.rds
-rw-r--r-- 1 bartek theorie 3.4G Oct 22 10:59 test_bootstrap_nlsfit_leave_out_004.rds
-rw-r--r-- 1 bartek theorie  27M Oct 22 11:00 test_bootstrap_nlsfit_leave_out_005.rds
-rw-r--r-- 1 bartek theorie 3.4G Oct 22 11:00 test_bootstrap_nlsfit_leave_out_006.rds
-rw-r--r-- 1 bartek theorie 3.4G Oct 22 11:01 test_bootstrap_nlsfit_leave_out_007.rds
[...]
```

**Comment by kostrzewa** [comment]
Alright, I also know why this was behaving crazily like this. The model function A was defined inside of another function B (which is itself called by `pv_call` in this case). As the model function is defined inside the scope of function B, R rightly assumes that this environment has to be attached for the function to work...

**Comment by kostrzewa** [comment]
@s6ygleee This means that you should also rewrite how you use `bootstrap.nlsfit` in analysis_flavor_singlet...

**Comment by kostrzewa** [comment]
@martin-ueding I think there might be instances of this kind also in LuescherAnalysis

**Comment by kostrzewa** [comment]
The only way to prevent this is to define model functions (or anything else which is passed to another function and may be stored in its return value) at the file scope.

**Comment by martin-ueding** [comment]
I commented on the other issue thinking along the same lines before reading these more recent comments. Yeah, then we have figured it out. Fit functions should not be defined inside a `function (param, value)`, then. Any additional parameters should be passed explicitly, we have the mechanism for that in `bootstrap.nlsfit`.

That's really the downside of managed languages: They do really well until you hit a subtle trap like this. And then you have to understand how everything below works to work around it. In C++ you would have it a bit more explicitly and in C you would not even think that abstractly about things anyway.

**Comment by kostrzewa** [comment]
Agreed to both points @martin-ueding

**Comment by s6ygleee** [comment]
Currently, I got an error for using bootsrap.nlsfit in the R code and wondering it is because of this issue or just my coding problem.
Then if I understood the above discussion correctly, should I need to rid of the stored return values in nlsfit before use it?

**Comment by martin-ueding** [comment]
What's the code and the error you get?

The change you need to do in your analysis code is to define fit functions outside of the `function (param, value) {` constructs that we have all over the LuescherAnalysis, and also the flavor singlet project. You do not need to do that, the only downside is that memory usage will be higher. If that does not pose a problem for you, you are fine for now.

**Comment by s6ygleee** [comment]
I see :) Then I think it is a coding problem. Because I got "Error in 1:(boot.R + 1) : argument of length 0" 
I also define fit functions inside the "function (param, value) {" construction but it seems it is not the problem for these errors.
Thank you

**Comment by kostrzewa** [comment]
Alright, closing as this is not a bug but a feature :weary:

**Comment by kostrzewa** [comment]
@s6ygleee 
>  I also define fit functions inside the "function (param, value) {" construction but it seems it is not the problem for these errors.

but it is one of the reasons why your R session uses so much memory....
