### ISSUE TITLE
bootstrap.nlsfit only uses correlated chi^2 if a CovMatrix is passed

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#189]
this is despite the fact that samples may be passed

**Comment by matfischer** [comment]
I encountered a weird error using the latest version of `bootstrap.nlsfit`. An error message popped up telling me that boot_r = 0 is not provided. From the documentation I couldn't find any error I made respectively old code which worked back then does not work anymore.

**Comment by martin-ueding** [comment]
@matfischer: The model function needs to accept `...` as a catch-all argument now. That in in the documentation of `bootstrap.nlsfit`: https://github.com/HISKP-LQCD/hadron/blob/master/man/bootstrap.nlsfit.Rd#L13

**Comment by kostrzewa** [comment]
This should also always work now, as long as you fit function accepts `...`, both the `optim` and `minpack.lm` code paths will work now.
