### ISSUE TITLE
Unused arguments at cf_weighted in gevp2cf

### ISSUE THREAD

**Issue by matfischer** [HISKP-LQCD/hadron#193]
cf_weighted creates a cf object which contains `weight.factor`, `weight.cosh` `weighted <- TRUE` but does not create `mass1` and `mass2` which is needed at gevp2cf. What was the idea of `mass1` and `mass2`? I guess we can just drop it out of the `cf_weighted` call at `gevp2cf?`

**Comment by kostrzewa** [comment]
See #184 in which @martin-ueding started work on this. If you think that the changes are appropriate, please go ahead and merge #184
