### ISSUE TITLE
roxygen2 version 7 formats differently

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#206]
@j-ostmeyer has found that roxygen2 version 7 will reflow the paragraphs of text. There is a compatibility mode which does not solve that particular problem. This means that if we keep checking in the generated files, we will get tons of changes whenever somebody else has worked on a file.

**Comment by kostrzewa** [comment]
yup, this has happened many times in the past already between your and my commits, I think at present there's not much that we can do, other than perhaps removing all of the Rd's that are now auto-generated (which are the majority)

**Comment by martin-ueding** [comment]
Or we all just go to the latest version of Roxygen, hoping that the latest is available for R versions 3.4 and 3.6.

**Comment by j-ostmeyer** [comment]
At least for the R versions 3.4 and 3.5 it's roxygen2 version 7.0.0.

**Comment by martin-ueding** [comment]
Okay, then it is easy and everybody just installs version 7.0.0 and we won't have any issues with it.
