### ISSUE TITLE
new_matrixfit does not show all points in plot

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#208]
By construction the `new_matrixfit` only passes the time slices of the correlator that are actually fitted to `bootstrap.nlsfit`. Then in consequence `plot.bootstrapfit` will only plot the points that have been used, which is not that useful. Rather we should have all the data in the plot. This will require changes to `new_matrixfit`, `bootstrap.nlsfit` and `plot.bootstrapfit`.

**Comment by kostrzewa** [comment]
completely agree that this would be highly useful

**Comment by martin-ueding** [comment]
What would be a sensible approach to do this? I just had the idea that one could just pass more _x_ and _y_ data to `bootstrap.nlsfit` together with a mask that would be applied. Then we would apply the mask early on but keep all the data and the mask in the result object. The `plot.bootstrapfit` would then have the data and still know which points should be used to generate the fit line and ribbon.

An alternative would be to also pass the additional points to `plot.bootstrapfit`, but that would effectively break `fit <- new_matrixfit(…); plot(fit)`.

**Comment by kostrzewa** [comment]
I think the mask as an optional argument is the only real way to go. When passed without a mask, all the data is fitted. When passed with a mask, the data, bootstrap samples and, possibly, covariance matrix, are restricted to the passed indices.

**Comment by urbach** [comment]
> I think the mask as an optional argument is the only real way to
> go. When passed without a mask, all the data is fitted. When passed
> with a mask, the data, bootstrap samples and, possibly, covariance
> matrix, are restricted to the passed indices.


why isn't the original data part of the returned object?

**Comment by martin-ueding** [comment]
The result of `new_matrixfit` is a `bootstrapfit` object. The `bootstrap.nlsfit` function is only passed the data corresponding to the time slices that are to be fitted. The other time slices were of no interest to the actual fit. This pull request changes exactly this by adding the `mask` parameter to `bootstrap.nlsfit` such that `new_matrixfit` can pass the fit range in terms of a mask to lay over the data. Then in `plot.bootstrapfit` the additional points will be shown.
