### ISSUE TITLE
bootstrap.nlsfit, get.errors, correlated fit, CovMatrix = NULL ==> incorrect dy

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#210]
https://github.com/HISKP-LQCD/hadron/blob/6867cc2f5ee45a3ed958e54aded50543ba4a3ae9/R/bootstrap.nlsfit.R#L195

When a correlated fit is done and `CovMatrix` is passed as `NULL`,  `W` is computed from the bootstrap samples and the input data errors are in turn computed via

```r
dydx <- 1.0/diag(W)
```

~This all seems fine, except that the errors that are stored as part of the return value now depend on the quality of the inverse of the covariance matrix. When the inversion is problematic, values of `dy` stored in the return value do not correspond to the actual statistical errors of the data...~

This is just simply wrong...

**Comment by kostrzewa** [comment]
Besides, this is not correct in the first place. The errors, if they are taken from the covariance matrix, should be taken from the covariance matrix.

**Comment by kostrzewa** [comment]
@NikSchlage It seems that you made this particular choice, what was the reasoning there?

**Comment by kostrzewa** [comment]
@NikSchlage did you use this in production for published / to be published plots?

**Comment by NikSchlage** [comment]
@kostrzewa I did not make that choice, I only renamed dy -> W in line 195.

**Comment by NikSchlage** [comment]
@kostrzewa I also think that the inverse cov matrix is wrong. And yes, I used this already existing code (with my prior modifications) for my plot production.

**Comment by kostrzewa** [comment]
@NikSchlage Indeed, looking back in history this was introduced multiple times in different guises and moved around in the code.

Note that it might be a little unclear whether this was or was not present in versions of hadron used for production (unless you have the exact version of the code that you used lying around).

I think this might have found it's way into the code around July 2018 or so, at which point it was correct (as it dealt with a particular edge case in the logic tree). At some point beyond that, it is very difficult to figure out at which point, it moved out of this edge case. Beyond that it's even more difficult to follow what happened to the logic tree.

I would say there might be a possibility that the plots that you produced in fact had correct errors, but it's a bit hard to say.
