### ISSUE TITLE
Forcing masses and amplitudes to be positive

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#216]
With the `n_particles` fit we see that sometimes the amplitude drops to be negative. As discussed over at https://github.com/HISKP-LQCD/LuescherAnalysis/issues/110 we have either the `upper`/`lower` that are going to be available or using the exponential transformation.

The exponential transformation seems like the optimal way, but would require changes in the models and also their derivative. Also the post-processing would needed to be changed. We have the machinery for that, but we would require working on the models.

The `NParticlesModel` uses the `SingleModel`. So we would have to write a new `prediction`, `prediction_jacobian` and also `initial_guess` function for the models with the exponential prescription. We can either rework _all_ the models to become consistently exponential, or we just double the `MatrixModel`, `SingleModel` and then let the `NParticlesModel` inherit from the `ExponentialSingleModel` which inherits from the `ExponentialMatrixModel` which can then inherit the `MatrixModel`.

**Comment by urbach** [comment]
As an alternative, which might allow us to get away without thermal state removal see #215 , see also 
 
[hankel.pdf](https://github.com/HISKP-LQCD/hadron/files/3982873/hankel.pdf)

I think this could be applied directly. For one of the rho examples I found a plateau from very early Euclidean times on.

**Comment by martin-ueding** [comment]
The `lower` and `upper` seem to handle this quite well.
