### ISSUE TITLE
chisqr in `matrixfit` takes only integer values!? 

### ISSUE THREAD

**Issue by urbach** [HISKP-LQCD/hadron#219]
Try

    example(matrixfit)
    fitres$t[,4]

or look at the QQ-Plot. That is odd and certainly different from before...!

**Comment by kostrzewa** [comment]
The problem is that the last element of `$t` is not `chisq` per bootstrap sample but the number of iterations that the minimizer took. (see `fit.formatrixboot`)

There'll be a PR in a few seconds to fix the qqplot.

**Comment by kostrzewa** [comment]
As a side-node, there is also a bug in the function which, I think, only didn't surface because of R's partial matching. I'll fix that one too.

**Comment by kostrzewa** [comment]
One more reason to always prefer data frames over matrices for return values...
