### ISSUE TITLE
matrixModel and subtract.excitedstates are incompatible

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#22]
The function `subtract.excitedstates` in `R/matrixfit.R` calls `matrixModel` with five parameters whereas said function needs a sixth parameter `ov.sign.vec`. This overall sign seems to have been added later on without a default value.

How should this be resolved? By adding a default value of `+1` in `matrixModel` and leave `subtract.excitedstates` unchanged or by exposing the argument in `subtract.excitedstates` and let the user decide whether this argument needs to be passed?

Can one fit a negative correlator with `matrixfit` anyway? If not, then setting the default argument to `+1` seems to be the easiest solution.

**Comment by kostrzewa** [comment]
That's my fault. While no default argument is provided here, the argument is constructed in calling code (such as ```matrixfit```). I don't know what's better, but not only ```ov.sign.vec``` does not have a default value provided.

I would say that ```subtract.excitedstates``` should decide what to pass here, just like it does for the other parameters.

**Comment by kostrzewa** [comment]
> Can one fit a negative correlator with matrixfit anyway?

Sure.

**Comment by martin-ueding** [comment]
Maybe the linked commit resolves the issue?

**Comment by martin-ueding** [comment]
I think so.
