### ISSUE TITLE
hankel effmass t.idx is not the same length as effMass

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#225]
The effective mass generated by `hankel2effmass` has an inconsistent `t.idx` compared to `effMass`:

![Bildschirmfoto_002](https://user-images.githubusercontent.com/976924/71769872-95666580-2f26-11ea-908a-7a2179a685a9.png)

I'm not sure which one is correct at this point, I will have to understand the procedure a bit more first.

**Comment by martin-ueding** [comment]
I'm just using `1:length(effMass)` for now, at worst the effective masses are shifted by a few time slices.

**Comment by matfischer** [comment]
What t_0 value did you choose? As far as I have understood it, it is a function of t_0+\delta t..?

**Comment by urbach** [comment]
> What t_0 value did you choose? As far as I have understood it, it is a function of t_0+\delta t..? 

I'll check this, I might have forgotten to add one NA (or better n-1 NAs) at the end.

**Comment by urbach** [comment]
this is fixed by now, isn't it?

**Comment by martin-ueding** [comment]
Yes, they now all have the 48 elements for cA2.09.48 as desired.
