### ISSUE TITLE
Value of correlation function is redundant, inconsistencies

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#23]
A correlation function has the field `cf` which is a matrix containing the original samples. Then there is `cf0` which contains the mean of this matrix, that is the actual value. The bootstrap samples are stored in the value `cf.tsboot$t`. But there is a copy of the value as `cf.tsboot$t0`.

The function `subtract.excitedstates` modifies `cf`, `cf0` and `cf.tsboot$t`; but it does not modify `cf.tsboot$t0` to match `cf0`. Therefore said function breaks an unwritten invariant of the cf-class.

I see two possible solutions:

- Fix the function such that `cf.tsboot$t` is updated accodingly.
- Remove the redundant field in the cf-class everywhere.

What would make more sense?

**Comment by kostrzewa** [comment]
The existence of ```cf.tsboot$t0``` is a consequence of our storing the return value of the ```tsboot``` call. ```cf.tsboot$t0``` should be updated after excited state subtraction.

**Comment by martin-ueding** [comment]
There already is the line `cf$cf.tsboot$t0[ii] <- cf$cf0[ii]`. Therefore this issue seems to be resolved.
