### ISSUE TITLE
phi^4 analysis code upload

### ISSUE THREAD

**Issue by NikSchlage** [HISKP-LQCD/hadron#233]
@urbach @kostrzewa @martin-ueding Some weeks ago @kostrzewa asked me to upload my code/ functions I used for the phi^4 analysis. Is a new folder hadron/exec/phi4-analysis appropriate or is hadron the wrong place for my upload?

**Comment by kostrzewa** [comment]
I did? Oh, I see what you mean. Rather than the code for the phi^4 analysis, I was referring to the n-particle model and the addition of priors to `new_matrixfit`. I think we have all of that available now.

**Comment by martin-ueding** [comment]
@urbach, @NikSchlage and I just chatted about this in person. His analysis code is best housed in a separate repository in our GitHub organization.

**Comment by kostrzewa** [comment]
If you do want to archive the analysis in a common repo, you can create a new (private or public) project in the hiskp-lqcd orga.

**Comment by NikSchlage** [comment]
> If you do want to archive the analysis in a common repo, you can create a new (private or public) project in the hiskp-lqcd orga.

Ok, I'll create such a new project.
