### ISSUE TITLE
invCovMatrix blocks already blocked data again

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#24]
If bootstrap samples are used, via `boot.samples = TRUE`, then the bootstrap samples will be blocked again. If one passes `cf$cf.tsboot$t[, ii]` as `cf`, then the inversion routine will call `block.ts` again. This cannot be what we want in this case.

**Comment by urbach** [comment]
hmm, but if `boot.samples = TRUE`, the data is not blocked again, is it?

**Comment by urbach** [comment]
ah, yes, this is fixed now...
