### ISSUE TITLE
HDF5 correlator reading is a bottleneck

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#25]
For the sigma project I want to do some statistical analysis of the raw correlators. With the current set of momenta and operators and diagrams there are roughly 50k correlators (4 GB). My plan was to compute a few quantities per raw correlator:

- Maximum {integrated autocorrelation time per time slice}
- Maximum {relative error per time slice}
- Argmax of the above
- Median of {relative error per time slice for a few slices around t = 10}

This way we can see whether the blocking is chosen large enough and how the signals are.

I cannot load all the data into memory on my laptop (8 GB available) and I do not want to write a monolithic analysis that can only be run on qbig until it grows out of that machine as well. Therefore I am trying to do one correlator at a time.

The problem is that with the current data, which is not even half of one ensemble, and not including displacements, it would take days on my laptop. For a four point diagram it would take say 20 hours on four cores and we have four of these. The two and three point diagrams take half and five minutes each, respectively.

From my system monitor the bottleneck seems to be the CPU:

![screenshot_20180427_102737](https://user-images.githubusercontent.com/976924/39358968-4fecf48c-4a18-11e8-8f1f-4e04e6e51319.png)

Most importantly the SATA3 SSD is not the bottleneck as it seems.

What I do is a `h5ls` on the first configuration of each diagram and then load the available statistic of that correlator:

```r
        names <- h5ls(files[1])$name
        
        diagram_agg <- lapply(names, function (name) {
            cf <- readbinarycf(files = files,
                               T = param$extent_time,
                               hdf5format = TRUE,
                               hdf5name = name,
                               hdf5index = c(1, 2))
            
            shifted <- takeTimeDiff.cf(cf)
            uw <- uwerr.cf(shifted)
```
Running this through R's sampling profiler shows that almost all time is spend in the reading routine and the computation is 2% of the time:

![screenshot_20180427_123332](https://user-images.githubusercontent.com/976924/39359020-8da42bba-4a18-11e8-9619-c11e35d810e5.png)

Digging deeper into the `readbinarycf` function shows that most time is spend in the `h5read` and `h5ls`, which are not our functions:

![screenshot_20180427_124629](https://user-images.githubusercontent.com/976924/39359170-23dad584-4a19-11e8-92ee-2c138023343c.png)

The data is stored such that for each diagram and configuration there is one HDF5 file. Extracting one correlator from all configurations is maximally inefficient because each time we have to load every file and extract just a sliver from it. As the `h5ls` calls take up half the time in `readbinarycf` this seems like a huge waste. Also within `h5read` we have 35% of the time spend with actual reading and the remainder spend with IO related. I would think that this is per file open and therefore opening less files would give a speed-up.

For the autocorrelation time we do need the whole statistic. But reading all diagrams does not scale in the RAM. I thought about “transposing” the files: There is one file per diagram with one HDF5-group per flavor-momentum-displacement-gamma combination which then contains the whole statistic. The disadvantage is that these files needs to be generated compiled again when one increases the statistic, but it might make loading much easier. This could be done once with a short Python script which loads and stores the data.

When building the GEVP later on I will have to load certain correlators in their full statistic as well. There the same issue will occur, though perhaps not every single correlator is actually read.

Is the performance problem a real problem or do I just have to accept that this will take two days *once*? Is this “transpose” option sensible? Do you have a better idea?

**Comment by martin-ueding** [comment]
I have created a little Python program that does this file “transposition”. The resulting files look like this:

![screenshot_20180428_114610](https://user-images.githubusercontent.com/976924/39395093-996665d6-4ada-11e8-9479-ad68361a8ba4.png)

One issue seems to be that RAM usage scales linearly with number of files read in. This seems that the memory management of Python does not free the intermediate buffers *or* that the file is kept in memory until it is written. Perhaps using `.flush()` will alleviate this problem.

The `readbinarycf` function would have to be changed such that it loads the full statistic from a given group. I would hope that this makes the process more efficient.

**Comment by kostrzewa** [comment]
I can confirm that reading larger datasets from hdf5 files leads to a difference balance between I/O operations and boilerplate. In #132 only about 8-10% of the time is spent in ```h5ls``` and over 50% with actual reading. The remainder is consumed by ```rhdf5```-internal boilerplate.

**Comment by martin-ueding** [comment]
As the HDF5 reading will be done by the projection application code (to be written), the performance of HDF5 in R does not really matter so much any more?

**Comment by martin-ueding** [comment]
Indeed, I haven't done much direct HDF5 reading, such that this does not seem to be an issue. Additionally the load seems to be within the `rhdf5` routines such that we cannot do much ourselves anyway.
