### ISSUE TITLE
Some exports fail in R/cf.R even though they are exports

### ISSUE THREAD

**Issue by matfischer** [HISKP-LQCD/hadron#259]
I don't know what's the reason for this issue as the exports seems to be proper and I can call the help of the needed functions but they are not available.

I cannot use the functions `'+.cf'` and `c.cf`. I even tried, on my Laptop, the most recent version of roxygen2 but I still cannot export these functions. Do you have any ideas?

**Comment by martin-ueding** [comment]
That's somewhat intentional. They are not exported explicitly but only registered as S3 methods. So when you do `+` on `cf` objects, this automatically resolves to `+.cf`. I had this weeks ago in all my code, just change the `+.cf` to a simple `+`.

**Comment by urbach** [comment]
so, can we close this?
