### ISSUE TITLE
travis fails again

### ISSUE THREAD

**Issue by urbach** [HISKP-LQCD/hadron#269]
argh...

ERROR: dependency ‘tinytex’ is not available for package ‘rmarkdown’

* removing ‘/home/travis/R/Library/rmarkdown’

The downloaded source packages are in

	‘/tmp/Rtmp3uQiXw/downloaded_packages’

Warning messages:

1: In install.packages(c("tikzDevice", "minpack.lm", "boot", "Rcpp",  :

  installation of package ‘tinytex’ had non-zero exit status

2: In install.packages(c("tikzDevice", "minpack.lm", "boot", "Rcpp",  :

  installation of package ‘rmarkdown’ had non-zero exit status

The command "Rscript -e 'install.packages(c("tikzDevice", "minpack.lm", "boot", "Rcpp", "rmarkdown"));if (!all(c("tikzDevice", "minpack.lm", "boot", "Rcpp", "rmarkdown") %in% installed.packages())) { q(status = 1, save = "no")}'" failed and exited with 1 during .

Your build has been stopped.

**Comment by kostrzewa** [comment]
Can you point to the travis run please so we can look at the whole log?

**Comment by kostrzewa** [comment]
It broke because my changes were removed in 52a65c8182673c74133fd7492ffe0d2d0214a9ac

**Comment by urbach** [comment]
> It broke because my changes were removed in 52a65c8182673c74133fd7492ffe0d2d0214a9ac

Hmm, sorry, how did that happen?

**Comment by urbach** [comment]
> Can you point to the travis run please so we can look at the whole log?

https://travis-ci.org/github/urbach/hadron/builds/681563382?utm_medium=notification&utm_source=email

**Comment by kostrzewa** [comment]
It happens, but there seem to be two things that broke apparently.

**Comment by kostrzewa** [comment]
Yeah, there must have been some travis-internal change yet again as I've gone back to 21be7c5728d9dbf52e3caa9a26f7e7a789dbced3 in the `fix_travis_again` branch and forced Travis to redo the builds. Both the PR and the Push build failed, so something else is going on.

**Comment by kostrzewa** [comment]
Probably the order of execution in `.travis.yml` has changed and the line `Rscript .travis_install_texlive.R`, which used to be in the `script:` section, does not get run before everything else any more. Without reading more about what changes travis have made, there's not much that I can do at this stage.

**Comment by kostrzewa** [comment]
I would guess that our issues come, in part, from the fact that "R for Travis-CI is not officially supported, but is community maintained."

**Comment by kostrzewa** [comment]
Maybe we should switch to CircleCI with a custom docker image?

**Comment by kostrzewa** [comment]
Seems like there was a major update on April 27th (https://github.com/travis-ci/travis.rb#190-april-27-2020). Could be that...

**Comment by urbach** [comment]
> Seems like there was a major update on April 27th (https://github.com/travis-ci/travis.rb#190-april-27-2020). Could be that...

yeah, its a bit anoying, probably your suggestion for changing the
platform is useful. But then we have to change everything again.

We could also run a check every night on QBiG, but only on master I'm
afraid.

**Comment by urbach** [comment]
> Seems like there was a major update on April 27th
> (https://github.com/travis-ci/travis.rb#190-april-27-2020). Could be
> that...

Not obvious something changed related to R...

**Comment by urbach** [comment]
the package `xfun` is the problem, but I don't understand why, because it is installed

    Error: package ‘xfun’ was installed before R 4.0.0: please re-install it
    Execution halted
    ERROR: lazy loading failed for package ‘tinytex’
    * removing ‘/home/travis/R/Library/tinytex’

Already tried to go back to `oldrel` for the R version and to put `xfun` explicitly, but this didn't help, see

**Comment by urbach** [comment]
hmm, but with my repo `urbach/hadron` it worked??

https://travis-ci.org/github/urbach/hadron/builds/681663096?utm_medium=notification&utm_source=email
