### ISSUE TITLE
under Windoof the tests fail

### ISSUE THREAD

**Issue by urbach** [HISKP-LQCD/hadron#273]
[hadron-windoof-00check.log](https://github.com/HISKP-LQCD/hadron/files/4560245/hadron-windoof-00check.log)

does someone have a win installation to test this?

**Comment by j-ostmeyer** [comment]
Ok, I'll look into it.

**Comment by j-ostmeyer** [comment]
Sorry, but I don't even manage to reach this stage. I simply can't make R link to the GSL.

**Comment by urbach** [comment]
> Sorry, but I don't even manage to reach this stage. I simply can't make R link to the GSL.

hmm, I used

devtools::check_win_release()

Its then updloaded to somewhere and I get the results as an email. But
there I cannot debug. Can one disable tests @martin-ueding ? I know
thats dirty, but I really don't want to spent time with windows.

**Comment by j-ostmeyer** [comment]
In the log-file gsl is not even mentioned. I wonder how hadron is compiled there.

**Comment by urbach** [comment]
> In the log-file gsl is not even mentioned. I wonder how hadron is compiled there.

no idea (and frankly speaking, I don't care... ;) )

**Comment by kostrzewa** [comment]
> no idea (and frankly speaking, I don't care... ;) )

do the checks run through on MacOS X? If so, we might get away with simply ignoring Windows, or do I read the following incorrectly? " Package authors should make all reasonable efforts to provide cross-platform portable code. Packages will not normally be accepted that do not run on at least two of the major R platforms. Cases for Windows-only packages will be considered, but CRAN may not be the most appropriate place to host them. "

**Comment by urbach** [comment]
> > no idea (and frankly speaking, I don't care... ;) )
> 
> do the checks run through on MacOS X? If so, we might get away with simply ignoring Windows, or do I read the following incorrectly? " Package authors should make all reasonable efforts to provide cross-platform portable code. Packages will not normally be accepted that do not run on at least two of the major R platforms. Cases for Windows-only packages will be considered, but CRAN may not be the most appropriate place to host them. "

yes, thats another possibility! But I also don't have access to any MacOS...

**Comment by urbach** [comment]
With this `skip_on_os` the check runs through on Windows

https://win-builder.r-project.org/Gzv5Bq54KtIi/

Only one NOTE left, which I don't quite understand. In principle we could submit to CRAN now. But: do we want to wait for the remaining hankel stuff?

**Comment by urbach** [comment]
BTW: in 

https://win-builder.r-project.org/Gzv5Bq54KtIi/00install.out

you can see the installation log

**Comment by urbach** [comment]
how do we do the release? Just a tag?

**Comment by martin-ueding** [comment]
I believe that from the CRAN side one has to submit some kind of TAR file. On our side I'd just put a tag right where we bump it in the `DESCRIPTION`.

**Comment by urbach** [comment]
So, you mean we move the version to 3.0.3 and tag and submit. I'd like to merge the hankel stuff in, if possible?

**Comment by urbach** [comment]
for docu: the problem / WARNING related to the CFLAGS being set non-portable. This comes from

    ~/.R/Makevars

and can be changed with `usethis::edit_r_makevars()`

**Comment by martin-ueding** [comment]
Yes, I'd do a fresh version bump for the release to CRAN. In their log they even complained that the `Date` entry in `DESCRIPTION` was over a month old.

I've uploaded some data to help debugging the Hankel issue. I'm waiting for contractions now and have time to help with that.

**Comment by j-ostmeyer** [comment]
I'm glad the test on Windows pass now, although I did not manage to make hadron compile on my native Windows. GSL is not properly supported for Windows, no idea what kind of workaround they use.
I expect that many users will have the same problems as I have on Windows, just to keep that in mind. We should strongly recommend to install on Linux (or the Ubuntu subsystem on Windows 10) as long as this is not fixed.

**Comment by urbach** [comment]
I think on Windows packages come as binaries such that there is no need to install as we do...
