### ISSUE TITLE
predict.bootstrapfit

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#282]
In R there are model fitting functions like `lm`, `glm`. They all come with a function for the generic `predict`. Perhaps we can refactor the code in `plot.bootstrapfit` such that it is a proper prediction function. That would make it even more useful for the general audience.

**Comment by urbach** [comment]
> In R there are model fitting functions like `lm`, `glm`. They all
> come with a function for the generic `predict`. Perhaps we can
> refactor the code in `plot.bootstrapfit` such that it is a proper
> prediction function. That would make it even more useful for the
> general audience.

yes, I think that would be good. But not before CRAN...
