### ISSUE TITLE
how to properly write `\link[graphics]{plot}`

### ISSUE THREAD

**Issue by urbach** [HISKP-LQCD/hadron#287]
for CRAN I have taken these out, but if they are in, I get the error

    Non-file package-anchored link(s) in documentation object 'plotwitherror.Rd':
      ‘[graphics]{plot}’

and I don't know how to fix it.

**Comment by urbach** [comment]
there is a discussion [here](https://github.com/r-lib/roxygen2/issues/707), but currently I don't understand how to solve this for a generic function.

**Comment by urbach** [comment]
the solution seems to be often the same that I took, namely removing the link. Which somehow cannot be what is wanted...!?

**Comment by urbach** [comment]
Or one removes the package, that seems to work as well.

**Comment by urbach** [comment]
most annoying is that this warning appears only in the pretest after submission. None of my checks catch this!

**Comment by gmgeorg** [comment]
I found this thread after Google search on same issue.  After reading latest [R release notes](https://cran.r-project.org/doc/manuals/r-release/NEWS.html) the problem arises (now) because `plot` moved to **base** -- it's not in **graphics** anymore as of R 4.0.0.  I fixed the same error by replacing `link[graphics][plot]` with `\link[base][plot]`  and it passed all checks on CRAN.

**Comment by urbach** [comment]
I see, thanks!

**Comment by urbach** [comment]
but then its creating a `warning` on my system, since I'm not yet on R 4.0.0 .
And some of the check systems provided are also still on 3.X, so its a bit strange.

**Comment by gmgeorg** [comment]
I see.  Just as FYI: you wont be able to submit any CRAN packages anyways that don't pass all checks on R 4.0.0+ (R-devel is even on R 4.1 already).

**Comment by urbach** [comment]
yes, thanks, I know. But this I can test e.g. with `devtools`, however, in these tests the link problem did not show up.

**Comment by urbach** [comment]
fixed
