### ISSUE TITLE
extract_mass generic looks funny

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#291]
https://github.com/HISKP-LQCD/hadron/blob/0a10f4989324278d1162d3dc7e600f83fb4299d1/R/removeTemporal.cf.R#L308-L310

Should't this be `UseMethod('extract_mass', object)` or is the first parameter implicit?

**Comment by martin-ueding** [comment]
It's passed implicitly:

> You don’t pass any of the arguments of the generic to `UseMethod();` it uses deep magic to pass to the method automatically. The precise process is complicated and frequently surprising, so you should avoid doing any computation in a generic. To learn the full details, carefully read the Technical Details section in `?UseMethod`. — [Hadley, Advanced R](https://adv-r.hadley.nz/s3.html)
