### ISSUE TITLE
opposition to having `dplyr` as a basic requirement?

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#293]
Would there be any opposition to requiring `dplyr (>= 1.0.0)` as an `Imports:` dependency for the next release of hadron? I'm working on a class for working with bootstrapped and/or Gamma-analysed timeseries (for applications beyond correlation functions) and have been making rather heavy use of `dplyr`, such that almost every function that I add has a `requireNamespace('dplyr')` and assorted checks of the version. Since it's repetitive and error-prone, I would prefer an `Imports:` dependency with a minimum version, such that I can at least drop the version checks...

**Comment by martin-ueding** [comment]
I use the package a lot, so I'm happy if hadron would depend on it.

**Comment by urbach** [comment]
Fine for me.

**Comment by martin-ueding** [comment]
I will directly add it to the `master`.
