### ISSUE TITLE
Travis CI errors out for every build

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#299]
Somehow Travis CI is completely broken for us. I'll look into it.

**Comment by martin-ueding** [comment]
Summary: Using a newer Ubuntu version fixes the issues that we had from using an Ubuntu version from 2014 with newer and newer R versions.

**Comment by martin-ueding** [comment]
This is my diary for 2020-08-03 the current Travis CI errors. You don't have to read it, it is just all the detailed notes I took while diagnosing the issue.

The [last build on `master`](https://travis-ci.org/github/HISKP-LQCD/hadron/builds/714384927) has *errored*. That means that it could not complete for technical reasons other than failing tests. At the very end we have the following:

```console
$ Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
tinytex (0.24  -> 0.25  ) [CRAN]
rJava   (NA    -> 0.9-13) [CRAN]
staplr  (2.9.0 -> 3.0.0 ) [CRAN]
dplyr   (1.0.0 -> 1.0.1 ) [CRAN]
Skipping 1 packages not available: XML
Installing 5 packages: tinytex, rJava, XML, staplr, dplyr
Installing packages into ‘/home/travis/R/Library’
(as ‘lib’ is unspecified)
Error: (converted from warning) package ‘XML’ is not available (for R version 3.6.3)
Execution halted|
```

After this the build does not continue any more.

Looking into the R library on my laptop I can find a `xml2` (which likely is the GNOME one), but nothing else. Both for R 3.6 and 4.0.

There is a [package `XML` on CRAN](https://cran.r-project.org/), and we can directly see the issue: It needs R in version ≥ 4.0.0. Basically we just cannot build with an older version of R any more. As I don't have `XML` installed locally, it does not seem to strictly necessary to use hadron, though.

In our `.travis.yml` we have the following line:

```yaml
warnings_are_errors: true
```

This means that all sorts of warnings will be promoted to errors if they happen within an R session. I see ways to go forward:

1.  We can just allow warnings again. If this package is not strictly needed, then the warning will just pass. But then we will allow warnings to creep in again, and then we need some stabilization period before we can submit to CRAN again. We really don't want that.

2.  Just test on R 4.0 as that will become the standard going forward anyway.

3.  Remove the dependencies such that it still works with R 3.6. I am not sure whether this is really needed so much, as we can install newer versions of R on QBIG already and other distributions will catch up eventually.

# Finding the XML dependency

I want to see whether the dependency can be lifted first, so I check try the code that produces this dependency on my laptop with R 4.0.

The first one does not seem to bring that up.

```r
> deps <- remotes::dev_package_deps()
> deps$package
 [1] "rlang"      "glue"       "digest"     "ellipsis"   "magrittr"  
 [6] "vctrs"      "purrr"      "utf8"       "assertthat" "pkgconfig" 
[11] "pillar"     "lifecycle"  "fansi"      "crayon"     "cli"       
[16] "stringi"    "tidyselect" "tibble"     "R6"         "generics"  
[21] "Rcpp"       "stringr"    "dplyr"      "abind"
```

The second command gives the following output:

```r
> remotes::install_deps(dependencies = TRUE)
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                              
 2: CRAN packages only               
 3: None                             
 4: xfun      (0.14  -> 0.16 ) [CRAN]
 5: glue      (1.3.2 -> 1.4.1) [CRAN]
 6: vctrs     (0.3.1 -> 0.3.2) [CRAN]
 7: tinytex   (0.23  -> 0.25 ) [CRAN]
 8: jsonlite  (1.6.1 -> 1.7.0) [CRAN]
 9: htmltools (0.4.0 -> 0.5.0) [CRAN]
10: knitr     (1.28  -> 1.29 ) [CRAN]
11: rmarkdown (2.2   -> 2.3  ) [CRAN]
12: dplyr     (1.0.0 -> 1.0.1) [CRAN]]

Enter one or more numbers, or an empty line to skip updates:
Installing 8 packages: rJava, XML, png, filehash, staplr, hash, tikzDevice, tictoc
```

So some of the packages that we use has an dependency on `XML`, as it shows up there. I stumbled across the [`pkgDepTools`](https://rdrr.io/bioc/pkgDepTools/), but in the end a simple grep was sufficient to find the culprit:

```console
$ grep XML */DESCRIPTION
staplr/DESCRIPTION:Imports: tcltk, stringr, assertthat, glue, XML, rJava
```

The `staplr` package manipulates PDF files and is listed in `Suggests`. As the previous commit on our `master` branch still built fine, there must have been a new release of the `XML` library in the meantime.

I take that the dependency is there for a reason, so we cannot remove it. We do need to have it installed during testing such that we can exercise all parts of the code, even those with only weak dependencies.

# Letting Travis CI use R 4.0

Then perhaps the easiest way is to do testing on R 4.0. Somebody put `oldrel` into the `.travis.yml`, sounds like purposefully downgrading. I'll try to use the latest version of R in the branch `fix-travis-ci`.

Just using `release` there seems to break the Ubuntu packages that need to be installed:

```
$ sudo apt-get install -y libgsl-dev texlive-extra-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgsl-dev
The command "eval sudo apt-get install -y libgsl-dev texlive-extra-utils " failed. Retrying, 2 of 3.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgsl-dev
The command "eval sudo apt-get install -y libgsl-dev texlive-extra-utils " failed. Retrying, 3 of 3.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgsl-dev
The command "eval sudo apt-get install -y libgsl-dev texlive-extra-utils " failed 3 times.
The command "sudo apt-get install -y libgsl-dev texlive-extra-utils" failed and exited with 100 during .
Your build has been stopped.
```

[Searching the Ubuntu archives](https://packages.ubuntu.com/search?keywords=libgsl-dev&searchon=names&suite=all&section=all) says that this package is available on all distributions after *Xenial*. The build worker uses *Trusty* as we specify it that way. Although it from April 2014, it still has support until April 2022. However, it does not have the `libgsl-dev` package. How did it work before, then? This was also provided via the PPA as one can see in older logs:

```
Get:10 http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu trusty/main amd64 libgsl-dev amd64 2.5+dfsg-6ubuntu2~ubuntu14.04.1~ppa1 [1,045 kB]
```

[Searching the PPA](https://launchpad.net/~marutter/+archive/ubuntu/c2d4u3.5/+packages?field.name_filter=libgsl-dev&field.status_filter=published&field.series_filter=) for that package, we find that it does not exist any more. So the author has removed this package from the PPA and we would need to get it from somewhere else. The easiest way would be a more recent Ubuntu image.

I will next try to use *Bionic* from April 2018. This seems to work!

**Comment by kostrzewa** [comment]
`staplr::staple_pdf` is used in `analysis_online` to have a portable way to concatenate PDF files. In principle, a rewrite of `analysis_online` could remove this dependency. For historical reasons the different parts of the analysis write individual PDF files which are then concatenated in the end. The individual parts could be made to just plot to the current graphics device (which is what I do now in the new version of `analysis_gradient_flow` which I hope to push in a few days).

So, if the `staplr` package is a problem, its removal won't be too much of a hassle.

**Comment by martin-ueding** [comment]
If we are happy to test on R 4.0 (which I think that we should anyway), then the `staplr` package is not a problem at all.
