### ISSUE TITLE
problem with h5_get_dataset 

### ISSUE THREAD

**Issue by urbach** [HISKP-LQCD/hadron#305]
the following fails on qubig

    library(stringr)
    library(hadron)
    f <- "/hiskp4/bartek/flavor_singlet/threept_fns/production_cB211a.072.64/0500/corr.0500.t126.h5"
    bn <- basename(f)
    ts <- str_split(bn, "\\.")[[1]][3]
    key <- paste0("/d+-g-u-g/", ts, "/gf4/pfx0pfy0pfz0/gi4/pix0piy0piz0")
    tmp <- h5_get_dataset(h5f = f, key = key)

with

    Error: Error in h5checktype(). Argument not of class H5IdComponent.

while it works when I use 

    rhdf5::h5read(file=f, name=key)

what am I doing wrong here?

**Comment by kostrzewa** [comment]
You need to open the HDF5 file first and pass the handle to `h5_get_dataset`. See https://github.com/kostrzewa/analysis_flavor_singlet/blob/7b6303e1034d8cb152787a96235c5c4a55015b17/paramval/ff/load_raw_3pt_conn_mom_shell.R#L66 for a usage example.

See also `?h5_get_dataset` in the hadron docs.

Besides that, however, can we talk about what you're trying to do? I don't really see the point in writing yet another independent analysis of the 3pt functions, to be honest... you'll hit all the same roadblocks (discussed at length in the past) and will have to solve all the same problems that have already been solved.

**Comment by kostrzewa** [comment]
Or is the idea to cross-check the eta/eta' analysis?

**Comment by kostrzewa** [comment]
Note that there are also functions to generate the keys, see `?correlators_key_meson_2pt` in hadron.

**Comment by urbach** [comment]
> You need to open the HDF5 file first and pass the handle to `h5_get_dataset`. See https://github.com/kostrzewa/analysis_flavor_singlet/blob/7b6303e1034d8cb152787a96235c5c4a55015b17/paramval/ff/load_raw_3pt_conn_mom_shell.R#L66 for a usage example.
> 
> See also `?h5_get_dataset` in the hadron docs.
> 
> Besides that, however, can we talk about what you're trying to do? I don't really see the point in writing yet another independent analysis of the 3pt functions, to be honest... you'll hit all the same roadblocks (discussed at length in the past) and will have to solve all the same problems that have already been solved.

Currently, I will just provide a cross-check for Konstantin, and for
this I have to read all the eta correlators. I'm not sure there is an
alternative to going through the procedure, is there?

I don't intend to re-write the 3pt analysis, of course, there I'd like
to extend what is available...

**Comment by kostrzewa** [comment]
> However, see here: https://github.com/kostrzewa/analysis_flavor_singlet/blob/master/R/cvc_readutils.R for ready-to-use functions to read correls, if you'd like to use them.

These are intended to be used in a paramval-based analysis, however, so I'm not sure if they are the best fit for what you're trying to do.

**Comment by urbach** [comment]
thanks a lot.

I'll go to look only on single configs, so I'm not sure what is faster at this point.

> There's also usage of these functions in https://github.com/kostrzewa/analysis_flavor_singlet/blob/master/paramval/ff/load_unshifted_raw_corrs.R, where the raw (complex,real) correlators are loaded, these are then later converted to cf and bootstrapped via https://github.com/kostrzewa/analysis_flavor_singlet/blob/master/paramval/ff/raw_cf_to_cf_and_bootstrap_2pt.R

**Comment by kostrzewa** [comment]
In that case definitely do it by hand, all the extra garbage will only slow you down ;)

**Comment by kostrzewa** [comment]
The only thing that might help is `hadron::raw_cf_data` which constructs a `raw_cf` from  a raw CVC correlator. This can then be turned into a `cf` using `raw_cf_to_cf`.

```{R}
  tictoc::tic("load_raw_2pt_conn_mom_shell: combine confs, shift, rescale and block average")
  raw_cf_list_corrid <- lapply_fn(
    X = 1:length(corrs_to_average),
    FUN = 
      function(corr_idx){
        # pre-allocate enough temporary memory for the correlator on all measurements
        corr <- array(as.complex(NA), dim = c(n_meas, value$extent_time, 1, 1))
        for( meas_idx in 1:n_meas ){
          # reshape the correlator data
          corr[meas_idx,,1,1] <- cf_list_measid_corrid[[meas_idx]][[corr_idx]]
        }
        if( any(is.na(corr)) ){
          stop("error: NA's found in combination of correlator over confs")
        }
        # convert to raw_cf, apply time shift to make everything relative to source
        # and average over the source time slices
        return(block.raw_cf(
          cf = shift.raw_cf(cf = raw_cf_data(raw_cf_meta(Time = value$extent_time),
                                                         data = corr),
                            places = files_df$src_ts),
          block_length = value$conn_ensemble_filelist$block_length)
        )
      }
    )
  tictoc::toc()
```
