### ISSUE TITLE
Installation from source fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#308]
Just to warn others: Installation from source is currently not possible on Ubuntu 22.04.

```
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

The issue arises when roxygen2 attempts to generate the documentation and the exports:

```
 $ ./document 
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: configure.ac: not using Automake
autoreconf: Leaving directory '.'
ℹ Updating hadron documentation
ℹ Loading hadron
Error: invalid version specification ‘0.68’
Execution halted
```

Scouring various forums has not brought any enlightenment (yet), why and where this version `0.68` comes up and why this errors out.

The traceback is also not very insightful, at least not for me:

```
> devtools::document()
ℹ Updating hadron documentation
ℹ Loading hadron
Error: invalid version specification ‘0.68’
> traceback()
20: stop(gettextf("invalid version specification %s", paste(sQuote(unique(x[!ok])), 
        collapse = ", ")), call. = FALSE, domain = NA)
19: .make_numeric_version(x, strict, .standard_regexps()$valid_R_system_version, 
        c("R_system_version", "package_version"))
18: R_system_version(paste(x[c("major", "minor")], collapse = "."))
17: package_version(list(major = 0, minor = VTE_VERSION))
16: ansi_has_hyperlink_support()
15: cli::style_hyperlink(paste0(basename(file), ":", line), paste0("file://", 
        file), params = c(line = line, col = 1))
14: paste0("[", cli::style_hyperlink(paste0(basename(file), ":", 
        line), paste0("file://", file), params = c(line = line, col = 1)), 
        "]")
13: link_to(tag$file, tag$line)
12: paste0(link_to(tag$file, tag$line), " @", tag$tag, " ", if (is.null(tag$raw)) ("(automatically generated) "), 
        message[[1]])
11: warn_roxy_tag(x, "must be a single paragraph")
10: roxy_tag_parse.roxy_tag_title(tokens[[i]])
9: roxy_tag_parse(tokens[[i]])
8: parse_tags(tokens)
7: .f(call = .l[[1L]][[i]], srcref = .l[[2L]][[i]], tokens = .l[[3L]][[i]], 
       ...)
6: purrr::pmap(list(call = as.list(parsed)[has_tokens], srcref = refs[has_tokens], 
       tokens = tokens[has_tokens]), block_create)
5: FUN(X[[i]], ...)
4: lapply(files, tokenize_file)
3: parse_package(base_path, env = NULL)
2: roxygen2::roxygenise(pkg$path, roclets)
1: devtools::document()
```

**Comment by urbach** [comment]
Hmm, I don't have a problem with linux mint (I think latest version) and

R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"



> Just to warn others: Installation from source is currently not possible on Ubuntu 22.04.
> 
> ```
> R version 4.1.2 (2021-11-01) -- "Bird Hippie"
> Copyright (C) 2021 The R Foundation for Statistical Computing
> Platform: x86_64-pc-linux-gnu (64-bit)
> ```
> 
> The issue arises when roxygen2 attempts to generate the documentation and the exports:
> 
> ```
>  $ ./document 
> autoreconf: export WARNINGS=
> autoreconf: Entering directory '.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force 
> autoreconf: configure.ac: tracing
> autoreconf: configure.ac: not using Libtool
> autoreconf: configure.ac: not using Intltool
> autoreconf: configure.ac: not using Gtkdoc
> autoreconf: running: /usr/bin/autoconf --force
> autoreconf: configure.ac: not using Autoheader
> autoreconf: configure.ac: not using Automake
> autoreconf: Leaving directory '.'
> ℹ Updating hadron documentation
> ℹ Loading hadron
> Error: invalid version specification ‘0.68’
> Execution halted
> ```
> 
> Scouring various forums has not brought any enlightenment (yet), why and where this version `0.68` comes up and why this errors out.
> 
> The traceback is also not very insightful, at least not for me:
> 
> ```
> > devtools::document()
> ℹ Updating hadron documentation
> ℹ Loading hadron
> Error: invalid version specification ‘0.68’
> > traceback()
> 20: stop(gettextf("invalid version specification %s", paste(sQuote(unique(x[!ok])), 
>         collapse = ", ")), call. = FALSE, domain = NA)
> 19: .make_numeric_version(x, strict, .standard_regexps()$valid_R_system_version, 
>         c("R_system_version", "package_version"))
> 18: R_system_version(paste(x[c("major", "minor")], collapse = "."))
> 17: package_version(list(major = 0, minor = VTE_VERSION))
> 16: ansi_has_hyperlink_support()
> 15: cli::style_hyperlink(paste0(basename(file), ":", line), paste0("file://", 
>         file), params = c(line = line, col = 1))
> 14: paste0("[", cli::style_hyperlink(paste0(basename(file), ":", 
>         line), paste0("file://", file), params = c(line = line, col = 1)), 
>         "]")
> 13: link_to(tag$file, tag$line)
> 12: paste0(link_to(tag$file, tag$line), " @", tag$tag, " ", if (is.null(tag$raw)) ("(automatically generated) "), 
>         message[[1]])
> 11: warn_roxy_tag(x, "must be a single paragraph")
> 10: roxy_tag_parse.roxy_tag_title(tokens[[i]])
> 9: roxy_tag_parse(tokens[[i]])
> 8: parse_tags(tokens)
> 7: .f(call = .l[[1L]][[i]], srcref = .l[[2L]][[i]], tokens = .l[[3L]][[i]], 
>        ...)
> 6: purrr::pmap(list(call = as.list(parsed)[has_tokens], srcref = refs[has_tokens], 
>        tokens = tokens[has_tokens]), block_create)
> 5: FUN(X[[i]], ...)
> 4: lapply(files, tokenize_file)
> 3: parse_package(base_path, env = NULL)
> 2: roxygen2::roxygenise(pkg$path, roclets)
> 1: devtools::document()
> ```
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/HISKP-LQCD/hadron/issues/308
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

-- 
Carsten Urbach
e-mail: ***@***.***
        ***@***.***
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
> Hmm, I don't have a problem with linux mint (I think latest version) and R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"

Does this include installation from source? Things work fine with the package, but I need stuff from the `tseries` branch which I haven't gotten around to getting ready for merge / release yet.

**Comment by kostrzewa** [comment]
Asked the roxygen2 authors for support: https://github.com/r-lib/roxygen2/issues/1369

**Comment by kostrzewa** [comment]
This is caused by https://github.com/r-lib/cli/issues/441, which has been fixed in very recent versions of `r-lib/cli`. As a workaround one can do `devtools::install_github('r-lib/cli')` to install the head commit directly from github.
