### ISSUE TITLE
gevp default parameters are almost always wrong

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#31]
The `gevp` function has parameters `element.order` and `matrix.size`. These are set up such that a GEVP of size 2×2 can be solved by default. The `matrix.size` is redundant because the first block in the function is

```r
  if(matrix.size^2 != length(element.order)) {
    stop("matrix.size^2 must be equal to length of element.order. Aborting...\n")
  }
```

One could also just use `matrix.size = as.integer(round(sqrt(length(element.order))))` and the requirement would also be satisfied automatically and the user would not be burdened with this parameter.

Also the correlation function has the `nrObs` field which already contains this information. Therefore a better default might be `element.ordering = 1:cf$nrObs`.

Changing this will of course break existing analysis scripts. However, I just managed to do a wrong GEVP which only took the first four matrix elements and interpreted this as a 2×2 problem and luckily it was not positive-definite such that I got a hard error.

**Comment by kostrzewa** [comment]
The ```nrObs``` is not necessarily meant for this purpose. One can construct ```cf``` objects which contain multiple correlation functions of different types which should definitely not be fitted together...

**Comment by urbach** [comment]
Indeed, I'd also like to be able to fit sub-matrices of a full correlation matrix. So I definitely do not want to use `nrObs` always. However, it might be a good default.

Anyhow, we can change this to make it more reasonable. I'm anyhow trying to give explicit arguments everywhere. @martin-ueding could make a proposal...?

**Comment by martin-ueding** [comment]
This is my proposal: https://github.com/HISKP-LQCD/hadron/tree/gevp-default-param

I have removed the `matrix.size` variable and let `element.order` default to all observations in the correlation function. This way a correlation function created with `c.cf` to contain just the relevant ones for the GEVP will work right away. If you want to only use a subset, you should be able to do that as well. The check for square GEVP is still present.

**Comment by martin-ueding** [comment]
No complaints in almost a week, I'll merge it in, then.
