### ISSUE TITLE
Move to Roxygen

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#36]
The documentation in R are the `Rd` files in the `man` directory. These had to be written by hand, now there exists Roxygen which can generate them. The documentation then sits above the functions and it works just like in C/C++ (Doxygen), Python (Epydoc, Sphinx), PHP (phpdoc), Java (JavaDoc).

Let's have the discussion whether we want to convert all the documentation to Roxygen (using `Rd2roxygen`) makes sense. Please feel free to edit this post below the line such that we have a concise collection of arguments for both cases.

---

Pro:

- The function signature including default values is automatically copied to the “usage” part of the documentation.
- Makes it easier to see whether all function arguments are documented.
- Updates to the source are more likely to be reflected in the documentation as well.
- Once we have marked all functions with `@export`, Roxygen can create the `NAMESPACE` file for us.
- Features like `@family` make it very easy to cross-link a bunch of related functions together. Otherwise one would have to manually insert `\link{…}` commands in each of the files, an O(N²) problem.
- Undocumented functions stand out.

Con:

- The source code files become longer due to all the documentation, especially when there are lots of examples.
- One has to call `devtools::document()` and check those files into git after each change to the documenation.

**Comment by kostrzewa** [comment]
The call to the document function could be done as a git hook, I believe.

**Comment by martin-ueding** [comment]
I had tried this with `clang-format` once and the problem is that changes introduced by the hook are not represented in the index. It is nice for aborting a commit if some test fails, but this does not alter things. What we could do is to abort the commit if Roxygen has changed something and then let the user try again.

**Comment by kostrzewa** [comment]
As a pre-commit hook, it should be possible to:

1. note the current state of the tree at this stage (some files may have modifications but were not added to the index on purpose, so we need to keep track of that)
2. execute ```develop::document()``` (or ```clang-format``` in other code-bases)
3. identify the files that have changed as a result
4. explicitly remove the files that were not added to the index before (1) [ probably need some python set operations here ]
5. add the remaining files to the index
6. continue with the commit, which should now also included the newly changed files

What do you think?

**Comment by kostrzewa** [comment]
Actually, since the hooks are not under version control by default (but rather, local to a repository), making this work in a team setting is a lot harder than I would have thought...

**Comment by martin-ueding** [comment]
That's not a big deal, one just have to check in a `setup-hooks` script which does this.

**Comment by martin-ueding** [comment]
We are currently checking in `configure` and all the generated `man/*.Rd` files. In principle there are three states:

- The git repository without any generated files
- A source distribution (like on CRAN) with generated files
- An installed package

We omit the middle step and let all our users (who are also developers) just install it from the git repository. Checking in those build files seems to be the consensus in the R community at large, though I personally really dislike this. In our Lüscher-Analysis package we do not check them in and tell users to run `devtools::document()` to get the documentation.

I understand that removing one step for users is a good thing. Johann just suggested that we could run `R -e 'devtools::document()'` as part of the `configure` script. This would mean that users have to install devtools and roxygen in order to use the library with its documentation. Alternatively we do proper releases on a platform like CRAN. Or we just stick to the current way and live with bloat in diffs and inconsistent code and documentation when somebody forgot to generate new documentation. I find this especially annoying in feature branches.

Is there a sensible route for excluding generated files from the git repository?

---

Independent of that I would like to convert all the existing documentation into Roxygen comments such that all these warnings about synopsis mismatches are eliminated by design. Also this will invite that the documentation is updated when the code is changed. Last time I asked there were concerns about the code-to-comment-ratio in the R code. I mostly navigate using ctags anyway, so I do not really mind this. Are you still against having all documentation in the R code?

**Comment by urbach** [comment]
> We are currently checking in `configure` and all the generated `man/*.Rd` files. In principle there are three states:
> 
> - The git repository without any generated files
> - A source distribution (like on CRAN) with generated files
> - An installed package
> 
> We omit the middle step and let all our users (who are also
> developers) just install it from the git repository. Checking in
> those build files seems to be the consensus in the R community at
> large, though I personally really dislike this. In our
> Lüscher-Analysis package we do not check them in and tell users to
> run `devtools::document()` to get the documentation.

well, there is no standard tool to generate the Rd files in R!

> I understand that removing one step for users is a good
  thing. Johann just suggested that we could run `R -e
  'devtools::document()'` as part of the `configure` script. This
  would mean that users have to install devtools and roxygen in order
  to use the library with its documentation. Alternatively we do
  proper releases on a platform like CRAN. Or we just stick to the
  current way and live with bloat in diffs and inconsistent code and
  documentation when somebody forgot to generate new documentation. I
  find this especially annoying in feature branches. 

In principle we can force these problems to be resolved, because they
are found in the travis run.

Of course, one would "only" need devtools and roxygen, but also all
the how many dependecies?

I'd not be against releases on CRAN, but that involves more than just
putting it there.

And we are not providing a classical product for "users". And its
simply reality that we are working with the current version on github,
and not with a release.

> Independent of that I would like to convert all the existing
> documentation into Roxygen comments such that all these warnings
> about synopsis mismatches are eliminated by design. Also this will
> invite that the documentation is updated when the code is
> changed. Last time I asked there were concerns about the
> code-to-comment-ratio in the R code. I mostly navigate using ctags
> anyway, so I do not really mind this. Are you still against having
> all documentation in the R code?

I don't think this will help for the documentation to be updated,
frankly speaking. Why should that be the case? And frankly again, I
don't like roxygen and Rstudio. But I'm flexible enough to adapt. So,
if this is seen as a major achievment and worth the amount of time
that needs to be put in, I can be convinced. But I'll not put time
into it myself.

**Comment by urbach** [comment]
Well let's also hear the others opinions! Any way of improving the docu has welcome and needed!

And, as I said, I could live with it! 

Am 13. November 2018 17:53:30 MEZ schrieb Martin Ueding <notifications@github.com>:
>Indeed, it requires a bunch of dependencies on the machines where it is
>used. This can indeed become annoying, so we need some mechanism of
>generating them before using the library. And a proper release on CRAN
>is a commitment, and since we depend on rhdf5 we cannot put it on CRAN
>anyway.>
>>
>Roxygen and RStudio are independent, but I see how we deviate from
>“base R” with this. I have the hope that documentation in the same file
>would nudge people into thinking about the documentation, but it can be
>just as ignored as in a separate file.>
>>
>Okay, let's just keep it as it currently is.

-- 
Carsten Urbach, www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
> Roxygen and RStudio are independent, but I see how we deviate from “base R” with this. I have the hope that documentation in the same file would nudge people into thinking about the documentation, but it can be just as ignored as in a separate file.

Okay, let's just keep it as it currently is.

I'm also in favor of doxygen-style documentation. However, it seems to me that for some of the functionality that we have in hadron, it becomes very cumbersome to write the documentation as Roxygen comments, especially when a lot of mathematical notation is required.

Also, I think this is still an issue: https://stackoverflow.com/questions/14041601/documenting-equations-with-deqn-and-roxygen

What we should do indeed is to add to configure some auto-detection magic for Roxygen (probably need to execute R for this and check for the return value of ```require("roxygen2")```). If it is found, we build the documentation. This way the chance of us as developers forgetting to check in compiled .Rd files is lower and users with roxygen2 available will have freshly built docs guaranteed. Yes, we alter the source directory in the build process, which is not great, but we need to make a choice somewhere..

As I said before, I'm very much in favour of using Roxygen for functions which can be documented with up 40 lines of documentation, say. But a function like ```matrixfit``` are already long and new things which we will need to write for baryons and more complicated correlation functions will require lots of mathematical notation to clarify what exactly is done and this will quickly become a pain in Roxygen.

**Comment by martin-ueding** [comment]
Markus had an interesting idea: We remove all the generated files on a new `develop` branch and then have a small script which basically does this:

```sh
git checkout master
git merge develop
R -e 'devtools::document()'
autoconf
git add configure man
git commit -m 'Automatic build and release'
```

This way we have clean diffs between various `develop` states but users can still pull down `master` and just use the library.
