### ISSUE TITLE
two-state fits to principal correlators

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#37]
Following Phys.Rev. D82, 034508 (2010) [section V], principal correlators can be fitted with a (single) discarded excited state by noting that the overlap factors are fully determined by the eigenvectors, the mass of the state and the value of the correlation function at the diagonalisation time t_0.

The principal correlator of state ```n``` has amplitude 1 at ```t_0```. As a result, one can fit the functional form

```(1-A_n) e^{-m_n(t-t_0)} + A_n e^{-m^\ast_n (t - t_0) }```

where ```m^\ast_n``` is an effective excited state contribution which is discarded.

**Comment by urbach** [comment]
Its not entirely clear whether this is applicable for our case. But we should try.

The problem I see is the usually rather small values of t_0 we have to use. Of course, we have to keep in mind that use non anisotropic gauges. Thus, their values of t_0=7 are actually not that big. Anyhow, we should try.

What is the general feeling: should we include this as an additional special case in `matrixfit`?
