### ISSUE TITLE
Allow fitting with “matrixfit” using only a subset of points

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#41]
With highly autocorrelated correlators, such as from the sigma project, the inversion of the covariance matrix becomes unstable. Therefore one should be able to use only a subset of points for the fit. This reduces the elements in the covariance matrix significantly and therefore improves the signal to noise ratio.

**Comment by j-ostmeyer** [comment]
Resolved in the recent pull request.
