### ISSUE TITLE
removeTemporal.cf overwrites c

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#47]
In `removeTemporal.cf`, there is `c <- 1.0` and later `c(…)` is used as concatenation. I initially thought that this would be a problem, but it isn't. You can overwrite `c` in your local environment and `c()` will still be a call to the `c` function. This only works with `c`, with `ls` it does not.

But perhaps it would be better to just rename this factor and have less confusion.

**Comment by kostrzewa** [comment]
indeed, c is a poor choice
