### ISSUE TITLE
bootstrap.effectivemass and bootstrap.cf have inconsistent default seeds

### ISSUE THREAD

**Issue by maowerner** [HISKP-LQCD/hadron#53]
The seeds are 1234 and 12345 respectively. Are they invoked or does bootstap.effectivemass read the seed from bootstrap.cf? I think it would be better to have the default behaviour be consistent

**Comment by kostrzewa** [comment]
bootstrap.effectivemass should not have a seed at this point

**Comment by kostrzewa** [comment]
If it does, then you need to upgrade your hadron version to the one where @martin-ueding introduced the various mixins for the cf class, which include the cf_boot mixin, which is tested for in bootstrap.effectivemass

**Comment by maowerner** [comment]
Your were right, the version was a bit older. Thanks!
