### ISSUE TITLE
matrixfit requires t0 argument although cf already knows its gevp_reference_time

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#57]
The `matrixfit` function now takes an additional argument `t0` that needs to be specified when one uses the `pc` model. We correlation function has the `gevp_reference_time` field in it when it inherits `cf_principal_correlator`. Therefore we already have all the information that `matrixfit` needs in the `cf` object.

**Comment by kostrzewa** [comment]
Indeed. I'm working on changing that and I've noticed that potentially ```t0``` is being used incorrectly further down the line. On the one hand, at the top of the ```matrixfit``` function, the index is calculated from ```t0``` to get ```t0p1```. Now, the ```pcModel``` uses ```t0``` and adds ```1``` by itself. As a result, I think ```t0``` should be passed in the minimization, no?

**Comment by kostrzewa** [comment]
see #59 for WIP and push there as you see fit

**Comment by urbach** [comment]
Hmm, I tried to use t0 on a consistent way... 

Am 2. August 2018 17:44:01 MESZ schrieb Bartosz Kostrzewa <notifications@github.com>:
>Indeed. I'm working on changing that and I've noticed that potentially
>```t0``` is being used incorrectly further down the line. On the one
>hand, at the top of the ```matrixfit``` function, the index is
>calculated from ```t0``` to get ```t0p1```. Now, the ```pcModel``` uses
>```t0``` and adds ```1``` by itself. In the calls to the minimizer,
>```t0p1``` is passed, which I don't think is correct.

-- 
Carsten Urbach, www.carsten-urbach.eu
