### ISSUE TITLE
Get rid of warnings from zero length arrows

### ISSUE THREAD

**Issue by urbach** [HISKP-LQCD/hadron#60]
`plotwitherror` produces warnings like

    Warning messages:
    1: In replayPlot(x) : zero-length arrow is of indeterminate angle and so skipped

heavily. Can we get rid of those?

**Comment by urbach** [comment]
@kostrzewa do you know, why they come about?

**Comment by kostrzewa** [comment]
Moving to ggplot2 would be an option, but I believe that we would first need to invest a significant amount of time to produce a production-quality theme. All the existing themes are (almost) completely unsuitable for physics publications, even when the tikz device is used for all text rendering. Also, I'm not sure if multiple error bars are supported, which plotwitherror can deal with in multiple ways.

**Comment by kostrzewa** [comment]
If both the theme and the multi-errors can be addressed, ggplot2 does lead to a reduction in code complexity, because the interface is very clean, if, perhaps, sometimes a bit restrictive.

**Comment by kostrzewa** [comment]
Despite the fact that the interface is so nice, I have a number of reservations with regard to ggplot2. It would be mandatory, for instance, to be able to place plot-internal legends. Square graphics are another important point. The "bw", "linedraw" and "classic" themes might be appropriate to use, but one would first have to see if we can produce some typical production-quality plots with them.

**Comment by urbach** [comment]
> Despite the fact that the interface is so nice, I have a number of
  reservations with regard to ggplot2. It would be mandatory, for
  instance, to be able to place plot-internal legends. Square graphics
  are another important point. The "bw", "linedraw" and "classic"
  themes might be appropriate to use, but one would first have to see
  if we can produce some typical production-quality plots with them.


I'm no fan of ggplot2, maybe I just have not seen a reasonable theme
yet. Anyhow, its only warnings, maybe I'll switch them off for the
arrows. 

--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by martin-ueding** [comment]
> Also, I'm not sure if multiple error bars are supported, which plotwitherror can deal with in multiple ways.

Do you mean something like this?

![multi-err](https://user-images.githubusercontent.com/976924/43647571-4c7c062c-9738-11e8-9afe-04eeb3865187.png)


```r
library(ggplot2)

df <- data.frame(x = 1:10,
                 y_val = runif(10, 1, 10),
                 y_err_stat = abs(rnorm(10, 1, 0.1)),
                 y_err_sys = abs(rnorm(10, 0.5, 0.1)))

p <- ggplot(df, aes(x = x)) +
    geom_errorbar(aes(ymin = y_val - y_err_stat - y_err_sys,
                      ymax = y_val + y_err_stat + y_err_sys),
                  color = '#aa0000') +
    geom_errorbar(aes(ymin = y_val - y_err_stat,
                      ymax = y_val + y_err_stat),linedraw
                  color = '#00aa00') +
    geom_point(aes(y = y_val),
               color = '#0000aa') +
    labs(title = 'Title',
         subtitle = 'Subtitle',
         caption = 'Caption',
         x = 'Independent Variable',
         y = 'Dependent Variable') +
    theme_bw()

print(p)

png('multi-err.png')
print(p)
dev.off()
```

> All the existing themes are (almost) completely unsuitable for physics publications

I guess I just do not see how ggplot2 is catastrophically worse than base-R plots and matplotlib. What are the things that you want and ggplot2 does not give you?

**Comment by urbach** [comment]
It looks ugly... Otherwise its fine.

Am 3. August 2018 16:25:53 MESZ schrieb Martin Ueding <notifications@github.com>:
>> Also, I'm not sure if multiple error bars are supported, which
>plotwitherror can deal with in multiple ways.
>
>Do you mean something like this?
>
>![multi-err](https://user-images.githubusercontent.com/976924/43647571-4c7c062c-9738-11e8-9afe-04eeb3865187.png)
>
>
>```r
>library(ggplot2)
>
>df <- data.frame(x = 1:10,
>                 y_val = runif(10, 1, 10),
>                 y_err_stat = abs(rnorm(10, 1, 0.1)),
>                 y_err_sys = abs(rnorm(10, 0.5, 0.1)))
>
>p <- ggplot(df, aes(x = x)) +
>    geom_errorbar(aes(ymin = y_val - y_err_stat - y_err_sys,
>                      ymax = y_val + y_err_stat + y_err_sys),
>                  color = '#aa0000') +
>    geom_errorbar(aes(ymin = y_val - y_err_stat,
>                      ymax = y_val + y_err_stat),linedraw
>                  color = '#00aa00') +
>    geom_point(aes(y = y_val),
>               color = '#0000aa') +
>    labs(title = 'Title',
>         subtitle = 'Subtitle',
>         caption = 'Caption',
>         x = 'Independent Variable',
>         y = 'Dependent Variable') +
>    theme_bw()
>
>print(p)
>
>png('multi-err.png')
>print(p)
>dev.off()
>```
>
>> All the existing themes are (almost) completely unsuitable for
>physics publications
>
>I guess I just do not see how ggplot2 is catastrophically worse than
>base-R plots and matplotlib. What are the things that you want and
>ggplot2 does not give you?

-- 
Carsten Urbach, www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
> Do you mean something like this?

Yes, but now you've actually drawn one line over another. The line with the internal error has a different colour than its endcaps (darker green vs. lighter green because green and red mixed in the anti-aliasing). The line for the second error should start where the first error ends.

> It looks ugly... Otherwise its fine.

One can argue about aesthetic preference, I guess, but it is certain that the plots are unsuitable for publication as they currently are.

**Comment by kostrzewa** [comment]
@martin-ueding One sometimes needs this kind of fine-grained level of control

[etmc_pion_vectorff_volume_limit.pdf](https://github.com/HISKP-LQCD/hadron/files/2257870/etmc_pion_vectorff_volume_limit.pdf)

and I find it difficult to imagine how to draw this plot with ggplot2

**Comment by urbach** [comment]
> > It looks ugly... Otherwise its fine.
> 
> One can argue about aesthetic preference, I guess, but it is certain that the plots are unsuitable for publication as they currently are.

yes, I was too unspecific. I should have said, I find it looks
ugly. But more seriously, I agree with you that it is in my opinion
not suitable for publications.
