### ISSUE TITLE
Comments with # and ##

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#69]
In the codebase I have seen comments starting with `# ` and `## `. What is the meaning of these, and is it a general R style rule?

**Comment by urbach** [comment]
> In the codebase I have seen comments starting with `# ` and `## `. What is the meaning of these, and is it a general R style rule?

my rule is that '#' is commented out code and '##' is a comment. My
indentation rule is accordingly different for the two...

**Comment by martin-ueding** [comment]
I have noted that on a `CONTRIBUTING.md` and I'll use that style for my comments here as well.
