### ISSUE TITLE
Doing Correlated fit using matrixfit. 

### ISSUE THREAD

**Issue by pittlerf** [HISKP-LQCD/hadron#72]
Hi,

I always get the error 
```
"[matrixfit] inversion of variance covariance matrix failed!\n"
```
when I try to use the matrixfit with the option useCov=TRUE independently of the fit range actually.

Could be that the parameter boot.l was not completely removed?
Then it might help to use instead of 
```r
invertCovMatrix(cf$cf.tsboot$t[,ii], boot.l=boot.l, boot.samples=TRUE), silent=TRUE)
```

```r
invertCovMatrix(cf$cf.tsboot$t[,ii], boot.l=cf$boot.l, boot.samples=TRUE), silent=TRUE)
```
Cheers

Feri

**Comment by martin-ueding** [comment]
This has been fixed in pull request #73.
