### ISSUE TITLE
bootstrap.nlsfit returns boot.R+1 elements

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#75]
In the bulk of the hadron library there are distinct `t` and `t0` fields for the bootstrap samples and the actual value. In the `bootstrap.nlsfit` function also has a `t0` but the `t` field has `boot.R + 1` elements and contains a copy of `t0` at `t[1]`. I find this very inconsistent and cumbersome to work with.

Just having it of length `boot.R` like the remainder of the code would be better I believe. Please make the change a new major version as it breaks the API.

**Comment by j-ostmeyer** [comment]
Resolved in recent pull request.
