### ISSUE TITLE
Termination reason of nls.lm opt.res$info: -1

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#79]
I found this output:

    Termination reason of nls.lm opt.res$info: -1

The documentation of `minpack.lm::nls.lm` only explains the termination reasons 0 to 9. Do you have an idea what -1 could be?

**Comment by kostrzewa** [comment]
Looking at the Fortran part of the source code of minpack.lm, negative values of ```info``` indicate user-terminated execution. See minpack.lm/src/lmdif.f:

```
c       info is an integer output variable. if the user has
c         terminated execution, info is set to the (negative)
c         value of iflag. see description of fcn. otherwise,
c         info is set as follows.
c
c         info = 0  improper input parameters.
c
c         info = 1  both actual and predicted relative reductions
c                   in the sum of squares are at most ftol.
c
c         info = 2  relative error between two consecutive iterates
c                   is at most xtol.
c
c         info = 3  conditions for info = 1 and info = 2 both hold.
c
c         info = 4  the cosine of the angle between fvec and any
c                   column of the jacobian is at most gtol in
c                   absolute value.
c
c         info = 5  number of calls to fcn has reached or
c                   exceeded maxfev.
c
c         info = 6  ftol is too small. no further reduction in
c                   the sum of squares is possible.
c
c         info = 7  xtol is too small. no further improvement in
c                   the approximate solution x is possible.
c
c         info = 8  gtol is too small. fvec is orthogonal to the
c                   columns of the jacobian to machine precision.
```

**Comment by martin-ueding** [comment]
Okay, this helps a bit. Thanks!

**Comment by kostrzewa** [comment]
I've encountered this too now for very heavy meson two-point functions which behave similarly to two-point functions at high momenta.

**Comment by martin-ueding** [comment]
I was a bit bewildered since I did not think that I sent an interrupt when getting these results. But now that you say it, I think that occurred in normal running. So indeed we need to figure out what it means.

**Comment by kostrzewa** [comment]
It only happens sometimes apparently. Had a run of the same analysis where it occurred 30+ times and another where it only happened around 6 times.

**Comment by martin-ueding** [comment]
Markus and I hit this `info = -1` again in the analysis, and he wondered what that means. Reading through the help again I realized that there is `info = 5` for exhausting `maxfev`, but there is no actual error for exhausting `maxiter`! Also what does “user terminated execution” for a non-interactive function? So it seems that this `-1` means that everything was on track, but then the number of iterations has been exhausted.

This can be seen with a simple test:

```r
model <- function (par, x) {
  par[1] * x + par[2]
}

x <- 1:10
y <- rnorm(length(x))
dy <- rep(1, length(x))

chi <- function (par) {
  (y - model(par, x)) / dy
}
```


```r
fit <- nls.lm(par = c(0, 0), fn = chi)
```

That fit has worked just fine. Reducing the number of iterations to a silly amount then gives `info = -1`:

```r
fit <- nls.lm(
  par = c(0, 0),
  fn = chi,
  control = nls.lm.control(maxiter = 2))
```

```
## Warning in nls.lm(par = c(0, 0), fn = chi, control = nls.lm.control(maxiter = 2)): lmdif: info = -1. Number of iterations has reached `maxiter' == 2.
```

I guess we should return the `message` and the `info` from the `wrapper` in `bootstrap.nlsfit` in order to give more information. Also the number of iterations should be a parameter to pass.

**Comment by martin-ueding** [comment]
We already give the `info` to the user, as an integer vector `info.boot`. The number of iterations should be a parameter, though.
