### ISSUE TITLE
bootstrap.nlsfit does not always need boot.R as a parameter

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#81]
I think making `boot.R = nrow(bsamples)` the default value would work just fine in the case of bootstrap samples such that one does not have to specify this redundantly. Or only access this parameter if one does not pass `bsamples`.

**Comment by kostrzewa** [comment]
Agreed, we should keep things consistent.

**Comment by martin-ueding** [comment]
In principle we can also extract `dy` and `dx` from `bsamples`.

But actually I think that we are doing two things here that should be split. There should be a very simple function `parametric_bootstrap(x, dx, boot.R)` that returns a matrix. And then the `bootstrap.nlsfit` should only take bootstrap samples, so the parameters `dy`, `dx` and `boot.R` would be taken away. I would not mind adding a convenience wrapper which does the parametric bootstrap and then calls the focused `bootstrap.nlsfit`.

 Would you agree?
