### ISSUE TITLE
Move to list-based intermediate format (medium- to long-term)

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#9]
I have recently started moving a substantial part of my own scripts to a list-based container format. This has the substantial benefit that one can use `mclapply` to significantly speed up anlyses as well as the reading of files using mulitple processes. Since the work is pre-schduled, the ordering of the output list is as expected.

I have taken the approach that I store each bootstrap sample (of a correlator, say) as a list element and one could think about storing our bootstrap samples in the same way. Then the following works:

```
temp <- mclapply(X=data,FUN=function(x) { fit(x,...) })
```

The result can then relatively easily be transformed into an array using `unlist(temp)` as `data` for an array with specific dimensions. Sometimes one has to transpose in addition.

**Comment by urbach** [comment]
you mean instead of an array you want to use a list. `mclapply` is unfortunately not available in all R installations, e.g. on my laptop version. But shouldn't that also work with arrays, as long as you can apply `as.list` to it? I never tried...

**Comment by kostrzewa** [comment]
I'm not sure whether as.list will work for this, maybe. The alternative is to try ```snow``` which can also work on arrays and data frames, but I haven't tried this yet and I have no idea how big the overhead is. (I guess the "cluster launch" and "cluster stop" functions can be wrapped in some kind of convenience framework)

In any case the list is an intermediate format used just for the parallelization because the benefits of having arrays or data frames far outweigh the overhead of transforming back and forth.

What I've implemented for now is to use one list element per bootstrap sample (or fit range, depends what I'm doing) and this can then be passed straightforwardly to ```mclapply``` with very good scaling properties. The return value is a list which may contain ```try-error``` elements which can be filtered out (in case of convergence problems and the like). After that is done, I use ```unlist``` to get back an array for final analysis (I didn't do this in some cases and in retrospect that was a bad idea).

The last step seems to have minimal overhead so the gains from parallelizing are not lost. Since handling lists does away with all the indexing goodness of R, it really can only serve as an intermediate format. To be honest, the best thing would be to try the ```snow``` package and see if the cluster versions of apply are as fast as ```mclapply```, because the data handling with lists can become a bit of a pain...

As for the availability of the ```parallel``` package, it can always be installed and it is the default parallelization chosen by the R project, as far as I can tell...

**Comment by urbach** [comment]
yes, the `multicore` package can be installed. But then we need addition `if` statements to check for availability...

I'll have a look into `as.list` and how it would transform our arrays...

**Comment by kostrzewa** [comment]
```multicore``` doesn't exist anymore, it's ```parallel``` now and has become a standard part of R. As for the if statements, this can be solved by wrapping lapply which is what I do for debugging. If ```parallell``` is available and parallelization is wanted, mclapply is called, otherwise we fall back onto lapply.

**Comment by urbach** [comment]
it does exist for my linux version...

**Comment by kostrzewa** [comment]
Well yes, it does exist but it has been superceded by 'parallel' as far as I understood. Not that there is any issue with using either 'multicore' or 'parallel', this can easily be tested for in the wrapper.

**Comment by martin-ueding** [comment]
Are we talking about Linux Mint packages? For R I just went on to install them in my home directory.

I am voting to close this because there is absolutely no need to change the data format. One can just do the following:

```
results <- mclapply(1:row(m), function (row_idx) { exp(m[row_idx, ]) })
m2 <- do.call(rbind, results)
```

The `mclapply` (or `pbmclapply` for progress bar) returns a list of vectors. We then bind those together to a new matrix. Perhaps one has to be a bit more careful, but in principle I have been using this in my sigma analysis stuff. There is copying of data around, so that is not as nice as having it in-place or directly into the result matrix. But this way everything can easily be retrofitted.

**Comment by kostrzewa** [comment]
Yes, that's a workable solution. We should definitely do this wherever fits are bootstrapped.

**Comment by kostrzewa** [comment]
When the function that is applied to the bootstrap samples returns just a single number, the ```do.call(rbind, tmp)``` fails to produce the expected result... so one either has to force it to return a single-column, single-row matrix or deal with this case at the conversion stage...

**Comment by martin-ueding** [comment]
Depending on the resulting type, `rbind` or `c` is the function to use. One could use `sapply` which does simplifications depending on the return type of the function called. I found this to be too unpredictable to use in a library.

**Comment by kostrzewa** [comment]
unfortunately, ```c``` does not do the job... one ends up with a list of vectors. If we do make generalisations of this pattern, we'll need to have some tests around to make sure that we don't mess up accidentally.

**Comment by martin-ueding** [comment]
You wrote that `rbind` does not do the right thing when the list elements are vectors with a single element. But it seems to work just fine?

```
> do.call(rbind, list(1, 2))                                                       
     [,1]                                                                           
[1,]    1                                                                           
[2,]    2
```

**Comment by kostrzewa** [comment]
I believe that in the analysis in question, the list elements are one-item *named* vectors, whence the difference in behaviour which I've observed elsewhere already.

Hopefully I'll have some time to check this explicitly at some later stage, for now, onwards and upwards...

**Comment by martin-ueding** [comment]
With named vectors this is different, indeed:

```
> do.call(rbind, list(c(a = 1), c(b = 2)))
     a
[1,] 1
[2,] 2
> do.call(cbind, list(c(a = 1), c(b = 2)))
  [,1] [,2]
a    1    2
```

What is the desired result? A data frame? If so, then having a named vectors is probably the wrong thing because the names in a vector are row-names, whereas the names in a list are column-names as the former is a homogeneous and the latter a heterogeneous data structure.

**Comment by kostrzewa** [comment]
By the way: depending on what one does,

```
results <- mclapply(1:row(m), function (row_idx) { exp(m[row_idx, ]) })
```

is up to a factor of 30-40 slower than a single-threaded apply...
