### ISSUE TITLE
Publishing hadron on CRAN

### ISSUE THREAD

**Issue by martin-ueding** [HISKP-LQCD/hadron#95]
Via email there was the idea to publish hadron on CRAN. I am not sure whether the optional dependency of `rhdf5` from the BioConductor repository makes this impossible. Once we have figured that out, we can further discuss.

---

Collection of tasks:

- [x] The license is states as `GPL 3 or later` which is not automatically recognized. We should either just write `GPL-3` and state that other versions are fine in some text, or live with this.
- [x] Using `library` within the code is apparently something that should not be done, we should instead use `::` or `requireNamespace`. The problem with using `library` or `require` in package code is that it alters the search path for the user of the package. [It is recommended](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages) to instead use `requireNamespace('foo')` and then use `foo::bar`.
- [x] The dependency to `rhdf5` is not declared in the `DESCRIPTION`. I had tried to fix that but then Travis CI would fail. The dependency should be in there, though.
- [x] There is `boot:::ts.array` somewhere in the code, which is a no-go. We must not depend on implementation details that are not exported.
- [x] Fix warnings about probable errors.
- [x] Fix warnings about S3 naming inconsistencies.
- [x] Fix inconsistencies between function signatures and their hand-written documentation pages.
- [x] Document all parameters of already documented functions.
- [x] Document all functions
- [x] Document all data sets.
- [x] The compilation flags in `PKG_CFLAGS`, `-O3 -Wall`, are not portable. This need to be changed, perhaps R already passes sufficient optimization flags such that this is not needed?
- [x] The `hadron.so` exports some elements from the standard library, this likely is a mistake and needs fixing.
- [x] Use only ASCII characters in R code.

**Comment by martin-ueding** [comment]
Then we also have this one here:

> In principle, packages must pass R CMD check without warnings or significant notes to be admitted to the main CRAN package area.

Currently there are *many* warnings that need to be fixed before we get to this point. Even if we end up not this submitting to CRAN, fixing all the warnings will improve the check experience and likely also the code itself.

**Comment by martin-ueding** [comment]
Once we have CRAN for deployment, we can remove all the generated files from the git repository, right?

**Comment by martin-ueding** [comment]
Regarding the license, [this is their list](https://www.r-project.org/Licenses/). It seems that we shall use `GPL-3` and indicate in some text that later versions are applicable.

**Comment by martin-ueding** [comment]
There are a bunch of warnings like these:

```
Codoc mismatches from documentation object 'alphas':
alphas
  Code: function(mu, nl = 3, lam0 = 0.25, Nc = 3, Nf = 2, use.cimpl =
                 TRUE)
  Docs: function(mu, nl, lam0 = 0.25, Nc = 3, Nf = 2)
  Argument names in code not in docs:
    use.cimpl
  Mismatches in argument default values:
    Name: 'nl' Code: 3 Docs:
```

As these functions do not use Roxygen to automatically update the documentation, somebody has to copy the signatures over to the documentation.

**Comment by kostrzewa** [comment]
>  The compilation flags in PKG_CFLAGS, -O3 -Wall, are not portable. This need to be changed, perhaps R already passes sufficient optimization flags such that this is not needed?

Argh..

**Comment by martin-ueding** [comment]
> That would mean having to implement our own tsboot then

We could just copy the implementation of `tsboot:::ts.array` into our package. Then we have that exact same function but do not depend on the internals of a different package.

> Argh..

Packages have to compile on Windows as well if they are up for CRAN.

But I believe that those flags are not needed. On my Fedora system the following flags are added automatically:

```
-fpic
-O2
-g
-pipe
-Wall
-Werror=format-security
-Wp,-D_FORTIFY_SOURCE=2
-Wp,-D_GLIBCXX_ASSERTIONS
-fexceptions
-fstack-protector-strong
-grecord-gcc-switches
-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1
-m64
-mtune=generic
-fasynchronous-unwind-tables
-fstack-clash-protection
-fcf-protection
```

From my side these extra flags could just be dropped as the defaults seem to cover optimization and warnings already.

**Comment by martin-ueding** [comment]
I have replaced all the `printf` in the C code with `Rprintf`, now these warnings are all gone. While I was at it, I formatted all the code with one new clang-format configuration.

Also I removed the specific `CFLAGS` as it automatically supplied `-Wall` and `-O2` on my Fedora system. I guess that other Linux distributions behave the same way. This way be are not bound to GCC-like compilers, though we are not particularly interested in it anyway.

I believe that the only thing to do is to add documentation for everything that is not documented yet.

**Comment by martin-ueding** [comment]
I have added a little script `./check` that you can run locally to get the package checked. Using `R CMD check .` is not recommended as it will stumble across the git repository and other things.

**Comment by kostrzewa** [comment]
@martin-ueding R says that only ASCII characters should be used in R code. ```bootstrap.nlsfit.R``` apparently contains non-ASCII characters.

**Comment by martin-ueding** [comment]
Yeah, that was probably me with the use of typographic quotes (“”). I can easily fix that with Vim (https://stackoverflow.com/questions/16987362/how-to-get-vim-to-highlight-non-ascii-characters).

**Comment by martin-ueding** [comment]
I have replaced the non-ASCII characters in that file.

**Comment by urbach** [comment]
now there are lots of new Notes and Warnings (4 WARNINGs, 7 NOTEs).

How can we find a way to get this ready to be submitted to CRAN and not everyone introducing WARNINGS and NOTES...

**Comment by martin-ueding** [comment]
I'd say we should just pick some version of `master`, make that warning free and then submit that to CRAN.

Then we likely should make it a policy that no warnings or errors are allowed for pull requests from now on.

**Comment by urbach** [comment]
shall we switch the warnings on now on travis?

**Comment by martin-ueding** [comment]
Yes please, let's keep the code warning free with every pull request such that we can always release to CRAN.

**Comment by urbach** [comment]
oh, its already so in `.travis.yml` ...

**Comment by urbach** [comment]
then I can close this here...
